import {dateKey,addDays,minutes} from './domain.js';
const check=(ok,msg)=>{if(!ok)throw Error(msg);};
const time=(date,t)=>new Date(`${date}T${t}:00`).getTime();
const stampValid=x=>typeof x==='string'&&Number.isFinite(Date.parse(x));
function validDate(d){check(typeof d==='string'&&/^20\d\d-\d\d-\d\d$/.test(d)&&dateKey(new Date(d+'T12:00:00'))===d,'日期不正确');}
function reason(s){check(typeof s==='string'&&s.trim().length>0&&s.length<=200,'请填写原因（最多200字）');return s.trim();}
function validatePlan(p,month){check(p&&typeof p==='object','班次设置无效');validDate(p.from);check(p.from.startsWith(month),'生效日期须在本月');check(minutes(p.end)>minutes(p.start),'班次结束须晚于开始，不支持跨日');check(Array.isArray(p.weekdays)&&p.weekdays.length>0&&new Set(p.weekdays).size===p.weekdays.length&&p.weekdays.every(n=>Number.isInteger(n)&&n>=0&&n<=6),'请选择有效工作日');check(Number.isInteger(p.grace)&&p.grace>=0&&p.grace<=60,'宽限时间须为0～60分钟');}
export function saveDutyPlan(d,month,p){check(/^20\d\d-(0[1-9]|1[0-2])$/.test(month),'月份无效');const value={start:p.start,end:p.end,from:p.from,weekdays:[...p.weekdays],grace:Number(p.grace)};validatePlan(value,month);d.dutyPlans??={};d.dutyPlans[month]=value;}
function planFor(d,date){validDate(date);const p=d.dutyPlans?.[date.slice(0,7)];check(p&&date>=p.from,'请先设置该月份的班次与生效日期');check(p.weekdays.includes(new Date(date+'T12:00:00').getDay()),'该日期不是工作日，请先调整本月工作日');return {...p,weekdays:[...p.weekdays]};}
function rowFor(d,date){return (d.dutyRecords||[]).find(r=>r.date===date);}
export function punchDuty(d,action,now=new Date()){const date=dateKey(now);let r=rowFor(d,date);check(!r||r.status!=='leave','当日已请假，请先撤销请假');if(action==='in'){check(!r?.checkIn,'今日已上班打卡');const p=planFor(d,date);check(!(d.dutyRecords||[]).some(x=>x.checkIn&&!x.checkOut&&x.date!==date),'还有历史签退缺卡，请先补卡或撤销');r={date,plan:p,status:'work',checkIn:now.toISOString(),checkOut:null,manual:false,reason:'',edits:[]};d.dutyRecords??=[];d.dutyRecords.push(r);}else if(action==='out'){check(r?.checkIn,'请先上班打卡');check(!r.checkOut,'今日已下班打卡');check(now.getTime()>Date.parse(r.checkIn),'下班时间须晚于上班时间');r.checkOut=now.toISOString();}else throw Error('打卡操作无效');return r;}
function inputTimes(date,start,end,now){validDate(date);check(minutes(end)>minutes(start),'结束时间须晚于开始时间');check(time(date,end)<=now.getTime(),'不能补录未来时间');return {checkIn:new Date(time(date,start)).toISOString(),checkOut:new Date(time(date,end)).toISOString()};}
export function repairDuty(d,input,now=new Date()){const why=reason(input.reason),times=inputTimes(input.date,input.start,input.end,now),old=rowFor(d,input.date);check(old?.status!=='leave','请先撤销当日请假');const plan=old?.plan||planFor(d,input.date);const r={date:input.date,plan,status:'work',...times,manual:true,reason:why,edits:[...(old?.edits||[]),{at:now.toISOString(),reason:why,before:old?{checkIn:old.checkIn,checkOut:old.checkOut}:null}].slice(-20)};d.dutyRecords??=[];if(old)d.dutyRecords[d.dutyRecords.indexOf(old)]=r;else d.dutyRecords.push(r);return r;}
export function leaveDuty(d,date,why){reason(why);check(!rowFor(d,date),'当日已有记录，请先撤销再登记请假');const plan=planFor(d,date);d.dutyRecords??=[];d.dutyRecords.push({date,plan,status:'leave',checkIn:null,checkOut:null,manual:false,reason:why.trim(),edits:[]});}
export function classifyDuty(r,now=new Date()){if(r.status==='leave')return {...r,key:'leave',label:'请假',minutes:0};const late=!!r.checkIn&&Date.parse(r.checkIn)>time(r.date,r.plan.start)+r.plan.grace*60000,early=!!r.checkOut&&Date.parse(r.checkOut)<time(r.date,r.plan.end);let key='pending',label='待打卡';if(r.checkOut){key=late||early?'abnormal':'normal';label=[late?'迟到':'',early?'早退':''].filter(Boolean).join('、')||'正常';}else if(now.getTime()>=time(r.date,r.plan.end)){key='missing';label=r.checkIn?'缺下班卡':'缺上下班卡';}else if(r.checkIn){key='working';label=late?'已上班 · 迟到':'工作中';}else if(now.getTime()>time(r.date,r.plan.start)+r.plan.grace*60000){key='missing';label='缺上班卡';}return {...r,key,label,late,early,minutes:r.checkIn&&r.checkOut?Math.round((Date.parse(r.checkOut)-Date.parse(r.checkIn))/60000):0};}
export function dutyRows(d,month,now=new Date()){const rows=new Map((d.dutyRecords||[]).filter(r=>r.date.startsWith(month)).map(r=>[r.date,r]));const p=d.dutyPlans?.[month];if(p){let day=p.from;while(day.startsWith(month)){if(p.weekdays.includes(new Date(day+'T12:00:00').getDay())&&!rows.has(day))rows.set(day,{date:day,plan:p,status:'work',checkIn:null,checkOut:null,manual:false,reason:'',edits:[]});day=addDays(day,1);}}return [...rows.values()].map(r=>classifyDuty(r,now)).sort((a,b)=>b.date.localeCompare(a.date));}
export function courseState(l,now=new Date()){if(l.status==='leave')return {key:'leave',label:'请假'};if(l.status==='cancelled')return {key:'cancelled',label:'已取消'};const late=!!l.checkIn&&(!l.manual||!!l.attendanceEdits?.length)&&Date.parse(l.checkIn)>time(l.date,l.start)+300000,early=!!l.checkOut&&(!l.manual||!!l.attendanceEdits?.length)&&Date.parse(l.checkOut)<time(l.date,l.end);if(l.status==='completed')return {key:late||early?'abnormal':'normal',label:[late?'迟到':'',early?'早退':''].filter(Boolean).join('、')||'正常',late,early};if(now.getTime()>=time(l.date,l.end))return {key:'missing',label:l.checkIn?'缺下课卡':'缺上下课卡',late};if(l.status==='teaching')return {key:'teaching',label:late?'上课中 · 迟到':'上课中',late};return {key:'pending',label:'待上课'};}
export function repairCourse(d,id,input,now=new Date()){const l=d.lessons.find(l=>l.id===id);check(l&&!['leave','cancelled'].includes(l.status),'请先恢复课程为待上课');const why=reason(input.reason),times=inputTimes(l.date,input.start,input.end,now);check(time(l.date,l.end)<=now.getTime(),'课程尚未结束，暂不能补卡');l.attendanceEdits??=[];l.attendanceEdits.push({at:now.toISOString(),reason:why,before:{checkIn:l.checkIn,checkOut:l.checkOut,status:l.status}});l.attendanceEdits=l.attendanceEdits.slice(-20);Object.assign(l,times,{status:'completed',manual:true});}
export function leaveCourse(d,id,why){const l=d.lessons.find(l=>l.id===id);check(l?.status==='scheduled','只有待上课课程可请假');l.leaveReason=reason(why);l.status='leave';}
export function validateAttendance(d){if(d.dutyPlans!==undefined){check(d.dutyPlans&&typeof d.dutyPlans==='object'&&!Array.isArray(d.dutyPlans),'考勤班次格式无效');for(const [m,p]of Object.entries(d.dutyPlans)){check(/^20\d\d-(0[1-9]|1[0-2])$/.test(m),'班次月份无效');validatePlan(p,m);}}if(d.dutyRecords!==undefined){check(Array.isArray(d.dutyRecords)&&d.dutyRecords.length<=10000,'上下班记录格式无效');const dates=new Set();for(const r of d.dutyRecords){check(r&&typeof r==='object','上下班记录无效');validDate(r.date);check(!dates.has(r.date),'上下班记录日期重复');dates.add(r.date);validatePlan(r.plan,r.date.slice(0,7));check(['work','leave'].includes(r.status)&&typeof r.manual==='boolean','上下班状态无效');check(typeof r.reason==='string'&&r.reason.length<=200,'原因格式无效');for(const k of ['checkIn','checkOut'])check(r[k]===null||(stampValid(r[k])&&dateKey(new Date(r[k]))===r.date),'上下班时间无效');check(!r.checkOut||(r.checkIn&&Date.parse(r.checkOut)>Date.parse(r.checkIn)),'上下班起止时间无效');if(r.status==='leave')check(!r.checkIn&&!r.checkOut&&r.reason.trim(),'请假记录无效');validateEdits(r.edits);}}for(const l of d.lessons){if(l.leaveReason!==undefined)check(typeof l.leaveReason==='string'&&l.leaveReason.length<=200,'请假原因无效');if(l.attendanceEdits!==undefined)validateEdits(l.attendanceEdits);}}
function validateEdits(edits){check(Array.isArray(edits)&&edits.length<=20,'补卡记录格式无效');for(const e of edits){check(e&&stampValid(e.at),'补卡时间无效');reason(e.reason);check(e.before===null||(e.before&&typeof e.before==='object'),'补卡历史无效');if(e.before)for(const k of ['checkIn','checkOut'])check(e.before[k]===null||stampValid(e.before[k]),'原打卡时间无效');}}
