import {validateAttendance} from './attendance.js';
import {validateSalaryData} from './salary.js';
export const emptyData = () => ({version:1, students:[], lessons:[]});
const id = () => globalThis.crypto?.randomUUID?.() || `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
const check = (ok,message) => {if(!ok) throw new Error(message);};
export function dateKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function addDays(day,n){const d=new Date(`${day}T12:00:00`);d.setDate(d.getDate()+n);return dateKey(d);}
export function cents(value){const s=String(value).trim();check(/^\d{1,6}(\.\d{1,2})?$/.test(s),'请输入有效金额（0～999999.99，最多两位小数）');return Math.round(Number(s)*100);}
export const money = n => (n/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
export function minutes(t){check(/^([01]\d|2[0-3]):[0-5]\d$/.test(t),'时间格式不正确');return Number(t.slice(0,2))*60+Number(t.slice(3));}
function validDate(s){check(typeof s==='string'&&/^20\d\d-\d\d-\d\d$/.test(s)&&dateKey(new Date(`${s}T12:00:00`))===s,'日期不正确（支持2000～2099年）');}
function text(value,max=100){return String(value??'').trim().slice(0,max);}
export function saveStudent(d,input){const name=text(input.name,40);check(name.length>0,'请填写学生姓名');const student={id:input.id||id(),name,subject:text(input.subject,40),rateCents:cents(input.rate),contact:text(input.contact,80),note:text(input.note,500),archived:!!input.archived,billingMinutes:Number(input.billingMinutes||60),selfRecruited:input.selfRecruited===true||input.selfRecruited==='true'};const i=d.students.findIndex(s=>s.id===student.id);if(i<0)d.students.push(student);else d.students[i]=student;return student;}
export function amount(l){return l.billingMinutes===90?Math.ceil((minutes(l.end)-minutes(l.start))/90)*l.rateCents:Math.round((minutes(l.end)-minutes(l.start))*l.rateCents/60);}
function validateLesson(d,l,ignoreId){validDate(l.date);check(minutes(l.end)>minutes(l.start),'结束时间必须晚于开始时间，不支持跨日课程');check(d.students.some(s=>s.id===l.studentId),'请选择有效学生');check(Number.isSafeInteger(l.rateCents)&&l.rateCents>=0&&l.rateCents<=99999999,'课酬单价不正确');check(!d.lessons.some(x=>x.id!==ignoreId&&!['cancelled','leave'].includes(x.status)&&x.date===l.date&&x.start<l.end&&x.end>l.start),`${l.date} ${l.start} 与已有课程冲突，请调整时间`);}
export function scheduleLessons(d,input){const count=Number(input.repeat||1);check(Number.isInteger(count)&&count>=1&&count<=12,'重复周数必须为1～12');validDate(input.date);const lessons=[];for(let i=0;i<count;i++){const l={id:id(),studentId:input.studentId,date:addDays(input.date,i*7),start:input.start,end:input.end,rateCents:cents(input.rate),billingMinutes:Number(input.billingMinutes||60),subject:text(input.subject,40),note:text(input.note,500),status:'scheduled',paid:false,checkIn:null,checkOut:null,manual:false};validateLesson(d,l);lessons.push(l);}d.lessons.push(...lessons);return lessons;}
export function updateLesson(d,lessonId,input){const l=d.lessons.find(x=>x.id===lessonId);check(l?.status==='scheduled','只有待上课课程可以修改；已完成课程请先撤销完成');const updated={...l,date:input.date,start:input.start,end:input.end,rateCents:cents(input.rate),billingMinutes:Number(input.billingMinutes||60),subject:text(input.subject,40),note:text(input.note,500)};validateLesson(d,updated,l.id);Object.assign(l,updated);return l;}
export function transition(d,lessonId,action,now=new Date()){const l=d.lessons.find(x=>x.id===lessonId);check(l,'找不到课程');const stamp=now.toISOString(),today=dateKey(now);if(['start','finish','complete'].includes(action))check(l.date<=today,'未来课程不能打卡或完成');switch(action){
 case 'start':check(l.status==='scheduled','仅待上课课程可以打卡');check(l.date===today,'历史课程请使用补录完成');check(!d.lessons.some(x=>x.status==='teaching'),'请先结束正在上课的课程');l.status='teaching';l.checkIn=stamp;break;
 case 'finish':check(l.status==='teaching','请先上课打卡');check(now.getTime()>=new Date(l.checkIn).getTime(),'下课时间不能早于上课时间');l.status='completed';l.checkOut=stamp;break;
 case 'complete':check(l.status==='scheduled','仅待上课课程可以补录');check(new Date(`${l.date}T${l.end}:00`)<=now,'课程还未结束，暂不能补录完成');l.status='completed';l.manual=true;l.checkIn=`${l.date}T${l.start}:00`;l.checkOut=`${l.date}T${l.end}:00`;break;
 case 'paid':check(l.status==='completed','仅已完成课程可以标记收款');l.paid=!l.paid;break;
 case 'cancel':case 'leave':check(l.status==='scheduled','请先撤销课程完成或打卡状态');l.status=action==='cancel'?'cancelled':'leave';break;
 case 'restore':check(l.status!=='scheduled','课程已为待上课');validateLesson(d,l,l.id);l.status='scheduled';l.paid=false;l.checkIn=null;l.checkOut=null;l.manual=false;delete l.leaveReason;break;
 default:throw new Error('未知操作');}return l;}
export function summary(d,month){const rows=d.lessons.filter(l=>l.date.startsWith(month));const done=rows.filter(l=>l.status==='completed');return {earned:done.reduce((n,l)=>n+amount(l),0),paid:done.filter(l=>l.paid).reduce((n,l)=>n+amount(l),0),minutes:done.reduce((n,l)=>n+minutes(l.end)-minutes(l.start),0),completed:done.length,days:new Set(done.map(l=>l.date)).size,late:done.filter(l=>(!l.manual||!!l.attendanceEdits?.length)&&new Date(l.checkIn).getTime()>new Date(`${l.date}T${l.start}:00`).getTime()+300000).length,leave:rows.filter(l=>l.status==='leave').length,planned:rows.filter(l=>!['cancelled','leave'].includes(l.status)).length};}
export function parseBackup(raw){check(typeof raw==='string'&&new TextEncoder().encode(raw).length<=5_000_000,'备份文件过大');let d;try{d=JSON.parse(raw);}catch{throw new Error('文件不是有效的 JSON 备份');}check(d&&d.version===1&&Array.isArray(d.students)&&Array.isArray(d.lessons),'备份版本或格式不正确');check(d.students.length<=5000&&d.lessons.length<=20000,'备份记录数量过多');const ids=new Set();for(const s of d.students){check(s&&typeof s.id==='string'&&/^[A-Za-z0-9_-]{1,100}$/.test(s.id)&&!ids.has(s.id),'学生编号重复或无效');ids.add(s.id);check(typeof s.name==='string'&&s.name.trim().length>0&&s.name.length<=40,'学生姓名无效');check(Number.isSafeInteger(s.rateCents)&&s.rateCents>=0&&s.rateCents<=99999999,'学生时薪无效');check(typeof s.archived==='boolean','学生归档状态无效');for(const k of ['subject','contact','note'])check(typeof s[k]==='string'&&s[k].length<=500,'学生资料格式无效');}const lessonIds=new Set();let teaching=0;for(const l of d.lessons){check(l&&typeof l.id==='string'&&/^[A-Za-z0-9_-]{1,100}$/.test(l.id)&&!lessonIds.has(l.id),'课程编号重复或无效');lessonIds.add(l.id);check(ids.has(l.studentId),'课程关联的学生不存在');validDate(l.date);check(minutes(l.end)>minutes(l.start),'课程时间无效');check(Number.isSafeInteger(l.rateCents)&&l.rateCents>=0&&l.rateCents<=99999999,'课程单价无效');check(['scheduled','teaching','completed','cancelled','leave'].includes(l.status),'课程状态无效');check(typeof l.paid==='boolean'&&(!l.paid||l.status==='completed'),'未完成课程不能标记收款');check(typeof l.manual==='boolean','考勤来源无效');for(const k of ['subject','note'])check(typeof l[k]==='string'&&l[k].length<=500,'课程资料格式无效');for(const k of ['checkIn','checkOut'])check(l[k]===null||(typeof l[k]==='string'&&Number.isFinite(Date.parse(l[k]))),'打卡时间无效');if(l.status==='completed')check(l.checkIn&&l.checkOut&&Date.parse(l.checkOut)>=Date.parse(l.checkIn),'已完成课程缺少有效考勤');if(l.status==='teaching'){teaching++;check(l.checkIn&&!l.checkOut,'上课考勤无效');}if(['scheduled','leave','cancelled'].includes(l.status))check(!l.checkIn&&!l.checkOut&&!l.manual,'待上课或取消课程不应有考勤');}check(teaching<=1,'不能同时有多节正在上课的课程');validateSalaryData(d);validateAttendance(d);return d;}
