import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyData,saveStudent,scheduleLessons,updateLesson,transition,summary,parseBackup} from '../src/domain/domain.js';
const now = new Date('2026-09-24T12:00:00');
function fixture(){const d=emptyData();saveStudent(d,{name:'小林',subject:'数学',rate:'100.10'});return d;}
function lesson(d,extra={}){return scheduleLessons(d,{studentId:d.students[0].id,date:'2026-09-24',start:'09:00',end:'10:30',rate:'100.10',...extra})[0];}
test('90分钟按100.10元/小时，完成后计150.15元，未完成不计薪',()=>{const d=fixture(),l=lesson(d);assert.equal(summary(d,'2026-09').earned,0);transition(d,l.id,'complete',now);assert.equal(summary(d,'2026-09').earned,15015);assert.equal(summary(d,'2026-09').minutes,90);});
test('全局冲突检测；首尾相接允许，取消释放时段',()=>{const d=fixture(),l=lesson(d);assert.throws(()=>lesson(d,{start:'10:00',end:'11:00'}),/冲突/);lesson(d,{start:'10:30',end:'11:00'});transition(d,l.id,'cancel',now);lesson(d);assert.equal(d.lessons.length,3);});
test('每周重复如遇冲突整批不写入',()=>{const d=fixture();lesson(d,{date:'2026-10-01'});assert.throws(()=>lesson(d,{repeat:'3'}),/冲突/);assert.equal(d.lessons.length,1);});
test('单价快照不随学生调价，已收款按完成金额汇总',()=>{const d=fixture(),l=lesson(d);saveStudent(d,{...d.students[0],rate:'200'});transition(d,l.id,'complete',now);transition(d,l.id,'paid',now);assert.equal(summary(d,'2026-09').paid,15015);});
test('未来不能打卡/完成，不能重复签到或未上课签退',()=>{const d=fixture(),l=lesson(d,{date:'2026-09-25'});assert.throws(()=>transition(d,l.id,'complete',now),/未来/);assert.throws(()=>transition(d,l.id,'start',now),/未来/);assert.throws(()=>transition(d,l.id,'finish',now));});
test('真实打卡记录时间，六分钟迟到，完成后不能篡改课时',()=>{const d=fixture(),l=lesson(d);transition(d,l.id,'start',new Date('2026-09-24T09:06:00'));assert.throws(()=>transition(d,l.id,'start',now));transition(d,l.id,'finish',new Date('2026-09-24T10:31:00'));assert.equal(summary(d,'2026-09').late,1);assert.equal(summary(d,'2026-09').days,1);assert.throws(()=>updateLesson(d,l.id,{date:l.date,start:'09:00',end:'11:00',rate:'100'}));});
test('请假和取消不计薪，撤销完成清除收款和考勤',()=>{const d=fixture(),l=lesson(d);transition(d,l.id,'leave',now);assert.equal(summary(d,'2026-09').leave,1);assert.equal(summary(d,'2026-09').earned,0);transition(d,l.id,'restore',now);transition(d,l.id,'complete',now);transition(d,l.id,'paid',now);transition(d,l.id,'restore',now);assert.equal(l.paid,false);assert.equal(l.checkIn,null);assert.equal(summary(d,'2026-09').earned,0);});
test('拒绝空姓名、非法金额、日期、跨天与零时长',()=>{const d=fixture();for(const rate of ['NaN','-1','1.234','Infinity',''])assert.throws(()=>saveStudent(d,{name:'李',rate}));assert.throws(()=>saveStudent(d,{name:' ',rate:'1'}));for(const x of [{date:'2026-02-30'},{start:'23:00',end:'01:00'},{end:'09:00'},{start:'25:00'},{repeat:'100'}])assert.throws(()=>lesson(d,x));});
test('备份往返保留历史，非法关系/金额/重复ID被拒绝',()=>{const d=fixture();lesson(d);assert.deepEqual(parseBackup(JSON.stringify(d)),d);for(const mutate of [x=>x.lessons[0].studentId='missing',x=>x.lessons[0].rateCents=-1,x=>x.students.push({...x.students[0]}),x=>x.lessons[0].status='oops',x=>x.lessons[0].paid=true]){const x=structuredClone(d);mutate(x);assert.throws(()=>parseBackup(JSON.stringify(x)));}assert.throws(()=>parseBackup('{'));});
test('备份ID不能注入HTML属性',()=>{const d=fixture();d.students[0].id='x"><img src=x onerror=alert(1)>';assert.throws(()=>parseBackup(JSON.stringify(d)),/编号/);});
test('中文备份按UTF8字节限制，与安卓读写一致',()=>{const d=emptyData();for(let i=0;i<3500;i++)d.students.push({id:'s'+i,name:'甲',subject:'数学',rateCents:100,contact:'',note:'中'.repeat(500),archived:false});const raw=JSON.stringify(d);assert.ok(raw.length<5_000_000);assert.ok(new TextEncoder().encode(raw).length>5_000_000);assert.throws(()=>parseBackup(raw),/过大/);});
