import test from 'node:test';import assert from 'node:assert/strict';
import {createSyncEngine} from '../src/sync-engine.js';
const doc=n=>({n});
function setup(remote={revision:0,document:null,updatedAt:null}){let local=doc(0),meta={revision:0,baseline:null,dirty:false,pending:null},state;const disk={};const api=async(route,body)=>{if(!body)return structuredClone(remote);if(body.expectedRevision!==remote.revision){const e=Error('conflict');e.status=409;throw e;}remote={revision:remote.revision+1,document:body.document,updatedAt:'now'};return structuredClone(remote);};const engine=createSyncEngine({api,read:()=>local,readMeta:()=>meta,saveMeta:m=>{meta=structuredClone(m);},apply:(d,m)=>{local=structuredClone(d);meta=structuredClone(m);},archive:d=>{disk.archive=structuredClone(d);},isEmpty:d=>d.n===0,onState:s=>state=s});return {engine,edit:n=>{local=doc(n);meta.dirty=true;},read:()=>local,state:()=>state,remote:()=>remote,setRemote:r=>remote=r,meta:()=>meta,disk};}
test('空设备从服务端恢复；离线改动重连上传',async()=>{const f=setup({revision:2,document:doc(3),updatedAt:'now'});f.engine.start('a');await f.engine.sync();assert.deepEqual(f.read(),doc(3));f.edit(5);await f.engine.sync();assert.equal(f.remote().revision,3);assert.equal(f.remote().document.n,5);});
test('两个设备修改冲突保留本机，选择服务端前存档',async()=>{const f=setup({revision:1,document:doc(2),updatedAt:'now'});f.engine.start('a');await f.engine.sync();f.edit(5);f.setRemote({revision:2,document:doc(8),updatedAt:'now'});await f.engine.sync();assert.equal(f.state().status,'conflict');assert.equal(f.read().n,5);await f.engine.resolve('remote');assert.equal(f.disk.archive.n,5);assert.equal(f.read().n,8);});
test('首次双方都有独立数据时不自动覆盖',async()=>{const f=setup({revision:1,document:doc(3),updatedAt:'now'});f.edit(2);f.engine.start('a');await f.engine.sync();assert.equal(f.state().status,'conflict');assert.equal(f.remote().document.n,3);});
test('切账号后旧响应不能写入新账号',async()=>{let finish,applied=false;const e=createSyncEngine({api:()=>new Promise(r=>finish=r),read:()=>doc(0),readMeta:()=>({revision:0,baseline:null,dirty:false}),saveMeta(){},apply(){applied=true;},archive(){},isEmpty:()=>true,onState(){}});e.start('a');const pending=e.sync();e.start('b');finish({revision:1,document:doc(4)});await pending;assert.equal(applied,false);});
test('上传已提交但响应丢失时重用请求编号，不重复创建版本',async()=>{let local=doc(5),meta={revision:0,baseline:null,dirty:true},remote={revision:0,document:null},failed=false,lastRequest,status;const api=async(_,body)=>{if(!body)return remote;if(body.requestId===lastRequest)return remote;lastRequest=body.requestId;remote={revision:remote.revision+1,document:body.document};if(!failed){failed=true;throw Error('connection lost');}return remote;};const e=createSyncEngine({api,read:()=>local,readMeta:()=>meta,saveMeta:m=>meta=m,apply:(d,m)=>{local=d;meta=m;},archive(){},isEmpty:()=>false,onState:s=>status=s});e.start('a');await e.sync();assert.equal(status.status,'error');assert.ok(meta.pending);await e.sync();assert.equal(remote.revision,1);assert.equal(status.status,'synced');assert.equal(meta.pending,null);});
test('上传期间新增修改仍保留为待同步',async()=>{let local=doc(1),meta={revision:1,baseline:doc(0),dirty:true},finish,status;const e=createSyncEngine({api:async(_,body)=>body?new Promise(r=>finish=()=>r({revision:2,document:body.document})):({revision:1,document:doc(0)}),read:()=>local,readMeta:()=>meta,saveMeta:m=>meta=m,apply(){},archive(){},isEmpty:()=>false,onState:s=>status=s});e.start('a');const pending=e.sync();await new Promise(r=>setImmediate(r));local=doc(9);finish();await pending;assert.equal(local.n,9);assert.equal(meta.dirty,true);assert.equal(status.status,'pending');});
