import mysql from 'mysql2/promise';
import {readFile} from 'node:fs/promises';
import {randomUUID,createHash} from 'node:crypto';
import {validateDocument} from '../src/domain/sync-document.js';
const hash=s=>createHash('sha256').update(s).digest('hex');
function fail(status,message){const e=Error(message);e.status=status;throw e;}
export function databaseOptions(env=process.env){for(const k of ['DB_HOST','DB_USER','DB_PASSWORD','DB_NAME'])if(!env[k])throw Error('MySQL配置缺少 '+k);if(!/^[a-zA-Z0-9_]+$/.test(env.DB_NAME))throw Error('数据库名无效');return {host:env.DB_HOST,port:Number(env.DB_PORT||3306),user:env.DB_USER,password:env.DB_PASSWORD,database:env.DB_NAME,charset:'utf8mb4',connectionLimit:5,connectTimeout:10000,supportBigNumbers:true,bigNumberStrings:false};}
export async function openDatabase(options,legacyFile){const pool=mysql.createPool(options);
 const schemas=[`CREATE TABLE IF NOT EXISTS users(id VARCHAR(64) PRIMARY KEY,email VARCHAR(254) CHARACTER SET ascii COLLATE ascii_bin UNIQUE NOT NULL,created_at VARCHAR(32) NOT NULL,last_login_at VARCHAR(32) NOT NULL) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS sessions(hash CHAR(64) CHARACTER SET ascii PRIMARY KEY,user_id VARCHAR(64) NOT NULL,expires BIGINT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id),INDEX(expires)) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS documents(user_id VARCHAR(64) PRIMARY KEY,revision INT UNSIGNED NOT NULL,body LONGTEXT NOT NULL,updated_at VARCHAR(32) NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS versions(user_id VARCHAR(64) NOT NULL,revision INT UNSIGNED NOT NULL,body LONGTEXT NOT NULL,updated_at VARCHAR(32) NOT NULL,request_id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,PRIMARY KEY(user_id,revision),UNIQUE KEY request_key(user_id,request_id),FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS metadata(meta_key VARCHAR(64) PRIMARY KEY,value TEXT NOT NULL) ENGINE=InnoDB`];
 try{for(const sql of schemas)await pool.query(sql);}catch(e){await pool.end();throw e;}
 async function tx(fn){const c=await pool.getConnection();try{await c.beginTransaction();const value=await fn(c);await c.commit();return value;}catch(e){await c.rollback();throw e;}finally{c.release();}}
 const query=async(c,sql,params=[])=>{const [rows]=await c.execute(sql,params);return rows;};
 if(legacyFile){let old;try{old=JSON.parse(await readFile(legacyFile,'utf8'));}catch(e){if(e.code!=='ENOENT'){await pool.end();throw Error('旧账号文件读取失败，已停止迁移');}}if(old){if(old.version!==1||!Array.isArray(old.users)||!Array.isArray(old.sessions))throw Error('旧账号文件格式无效');await tx(async c=>{await c.query("INSERT IGNORE INTO metadata VALUES('accounts-imported','pending')");const rows=await query(c,"SELECT value FROM metadata WHERE meta_key='accounts-imported' FOR UPDATE");if(rows[0].value!=='pending')return;for(const u of old.users)await query(c,'INSERT IGNORE INTO users VALUES(?,?,?,?)',[u.id,u.email,u.createdAt,u.lastLoginAt||u.createdAt]);for(const s of old.sessions){if((await query(c,'SELECT id FROM users WHERE id=?',[s.userId])).length)await query(c,'INSERT IGNORE INTO sessions VALUES(?,?,?)',[s.hash,s.userId,s.expires]);}await query(c,"UPDATE metadata SET value=? WHERE meta_key='accounts-imported'",[new Date().toISOString()]);});}}
 const userView=r=>r?{id:r.id,email:r.email,createdAt:r.created_at,lastLoginAt:r.last_login_at}:null;
 const view=r=>r?{revision:r.revision,document:JSON.parse(r.body),updatedAt:r.updated_at}:{revision:0,document:null,updatedAt:null};
 const read=async id=>view((await query(pool,'SELECT * FROM documents WHERE user_id=?',[id]))[0]);
 return {accounts:{async login(email,token,now){return tx(async c=>{const stamp=new Date(now).toISOString();await query(c,'INSERT INTO users VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE last_login_at=VALUES(last_login_at)',[randomUUID(),email,stamp,stamp]);const u=(await query(c,'SELECT * FROM users WHERE email=?',[email]))[0];await query(c,'DELETE FROM sessions WHERE expires<=?',[now]);await query(c,'INSERT INTO sessions VALUES(?,?,?)',[hash(token),u.id,now+7*86400000]);return userView(u);});},async session(token,now){if(typeof token!=='string'||!/^[a-f0-9]{64}$/.test(token))return null;return userView((await query(pool,'SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.hash=? AND s.expires>?',[hash(token),now]))[0]);},async logout(token){if(typeof token==='string')await query(pool,'DELETE FROM sessions WHERE hash=?',[hash(token)]);}},
 sync:{read,async save(id,expected,requestId,document){if(!Number.isSafeInteger(expected)||expected<0||typeof requestId!=='string'||!/^[\w-]{1,100}$/.test(requestId))fail(400,'同步版本或请求编号无效');validateDocument(document);return tx(async c=>{const user=await query(c,'SELECT id FROM users WHERE id=? FOR UPDATE',[id]);if(!user.length)fail(401,'账号不存在');const repeated=(await query(c,'SELECT * FROM versions WHERE user_id=? AND request_id=?',[id,requestId]))[0];const current=(await query(c,'SELECT revision,body FROM documents WHERE user_id=?',[id]))[0];const previous=JSON.parse((repeated||current)?.body||'{}');const body=JSON.stringify(validateDocument({...document,appearance:document.appearance===undefined?previous.appearance:document.appearance,conversation:document.conversation===undefined?previous.conversation:document.conversation}));if(repeated){if(repeated.body!==body)fail(409,'请求编号已用于其他数据');return view(repeated);}const old=current;if((old?.revision||0)!==expected)fail(409,'另一台设备有更新，请先处理同步冲突');const revision=expected+1,stamp=new Date().toISOString();await query(c,'INSERT INTO documents VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE revision=VALUES(revision),body=VALUES(body),updated_at=VALUES(updated_at)',[id,revision,body,stamp]);await query(c,'INSERT INTO versions VALUES(?,?,?,?,?)',[id,revision,body,stamp,requestId]);await query(c,'DELETE FROM versions WHERE user_id=? AND revision<=?',[id,revision-30]);return {revision,document:JSON.parse(body),updatedAt:stamp};});},async history(id){return query(pool,'SELECT revision,updated_at AS updatedAt,OCTET_LENGTH(body) AS bytes FROM versions WHERE user_id=? ORDER BY revision DESC',[id]);},async version(id,revision){const r=(await query(pool,'SELECT * FROM versions WHERE user_id=? AND revision=?',[id,revision]))[0];if(!r)fail(404,'找不到该历史版本');return view(r);}},close:()=>pool.end(),pool};
}
