function fail(status,message){const e=Error(message);e.status=status;throw e;}
function number(value){const n=Number(value);if(!Number.isSafeInteger(n)||n<0)fail(400,'消息编号无效');return n;}
const threadView=r=>r?{id:r.id,email:r.email,status:r.status,updatedAt:r.updated_at}:null;
const messageView=r=>({id:r.id,role:r.role,text:r.body,createdAt:r.created_at});
export async function createHumanSupport(pool,{staffEmails=''}={}){
 const staff=new Set(staffEmails.split(',').map(s=>s.trim().toLowerCase()).filter(Boolean));
 const isStaff=user=>!!user&&staff.has(user.email.toLowerCase());
 function requireStaff(user){if(!isStaff(user))fail(403,'此账号没有人工客服权限');}
 const [columns]=await pool.query("SELECT CHARACTER_SET_NAME AS charset,COLLATION_NAME AS collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='users' AND COLUMN_NAME='id'");
 const {charset,collation}=columns[0]||{};if(!/^[a-zA-Z0-9_]+$/.test(charset||'')||!/^[a-zA-Z0-9_]+$/.test(collation||''))throw Error('账号表字符配置无效');
 const userColumn=`VARCHAR(64) CHARACTER SET ${charset} COLLATE ${collation}`;
 await pool.query(`CREATE TABLE IF NOT EXISTS support_threads(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id ${userColumn} NOT NULL UNIQUE,status VARCHAR(10) NOT NULL DEFAULT 'open',created_at VARCHAR(32) NOT NULL,updated_at VARCHAR(32) NOT NULL,staff_read_id BIGINT UNSIGNED NOT NULL DEFAULT 0,FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB`);
 await pool.query(`CREATE TABLE IF NOT EXISTS support_messages(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,thread_id BIGINT UNSIGNED NOT NULL,sender_id ${userColumn} NOT NULL,role VARCHAR(8) NOT NULL,body TEXT NOT NULL,request_id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,created_at VARCHAR(32) NOT NULL,FOREIGN KEY(thread_id) REFERENCES support_threads(id),FOREIGN KEY(sender_id) REFERENCES users(id),UNIQUE KEY request_key(thread_id,sender_id,request_id),INDEX(thread_id,id)) ENGINE=InnoDB`);
 async function query(c,sql,args=[]){return (await c.execute(sql,args))[0];}
 async function tx(fn){const c=await pool.getConnection();try{await c.beginTransaction();const value=await fn(c);await c.commit();return value;}catch(e){await c.rollback();throw e;}finally{c.release();}}
 async function read(thread,after){after=number(after);if(!thread)return {thread:null,messages:[],hasMore:false};const rows=await query(pool,'SELECT * FROM support_messages WHERE thread_id=? AND id>? ORDER BY id LIMIT 101',[thread.id,after]);return {thread:threadView(thread),messages:rows.slice(0,100).map(messageView),hasMore:rows.length>100};}
 async function own(user,c=pool,lock=false){return (await query(c,'SELECT * FROM support_threads WHERE user_id=?'+(lock?' FOR UPDATE':''),[user.id]))[0];}
 async function byId(id,c=pool,lock=false){const row=(await query(c,'SELECT t.*,u.email FROM support_threads t JOIN users u ON u.id=t.user_id WHERE t.id=?'+(lock?' FOR UPDATE':''),[number(id)]))[0];if(!row)fail(404,'会话不存在');return row;}
 return {isStaff,
  async start(user){return tx(async c=>{await query(c,'SELECT id FROM users WHERE id=? FOR UPDATE',[user.id]);const old=await own(user,c,true),stamp=new Date().toISOString();if(old){if(old.status==='closed')await query(c,"UPDATE support_threads SET status='open',updated_at=? WHERE id=?",[stamp,old.id]);}else await query(c,'INSERT INTO support_threads(user_id,created_at,updated_at) VALUES(?,?,?)',[user.id,stamp,stamp]);return {thread:threadView(await own(user,c))};});},
  getOwn:(user,after=0)=>own(user).then(t=>read(t,after)),
  async getStaff(user,id,after=0){requireStaff(user);return read(await byId(id),after);},
  async list(user,{q='',status=''}={}){requireStaff(user);if(typeof q!=='string'||q.length>254||!['','open','closed'].includes(status))fail(400,'筛选条件无效');const rows=await query(pool,`SELECT t.*,u.email,(SELECT body FROM support_messages m WHERE m.thread_id=t.id ORDER BY m.id DESC LIMIT 1) AS lastText,(SELECT COUNT(*) FROM support_messages m WHERE m.thread_id=t.id AND m.role='user' AND m.id>t.staff_read_id) AS unread FROM support_threads t JOIN users u ON u.id=t.user_id WHERE (?='' OR t.status=?) AND (?='' OR LOCATE(?,u.email)>0) ORDER BY t.updated_at DESC,t.id DESC LIMIT 200`,[status,status,q,q]);return {threads:rows.map(r=>({...threadView(r),lastText:r.lastText||'',unread:Number(r.unread)}))};},
  async send(user,id,{requestId,text}={}){const agent=id!==null;if(agent)requireStaff(user);if(typeof requestId!=='string'||! /^[\w-]{1,100}$/.test(requestId)||typeof text!=='string'||!text.trim()||text.length>2000)fail(400,'请输入1～2000字消息');text=text.trim();return tx(async c=>{const thread=agent?await byId(id,c,true):await own(user,c,true);if(!thread)fail(409,'请先点击转人工');const prior=(await query(c,'SELECT * FROM support_messages WHERE thread_id=? AND sender_id=? AND request_id=?',[thread.id,user.id,requestId]))[0];if(prior){if(prior.body!==text)fail(409,'请求编号已用于其他消息');return {message:messageView(prior)};}if(thread.status!=='open')fail(409,'会话已结束，请重新转人工');const recent=await query(c,'SELECT COUNT(*) AS total FROM support_messages WHERE sender_id=? AND created_at>?',[user.id,new Date(Date.now()-60000).toISOString()]);if(recent[0].total>=30)fail(429,'消息发送过于频繁，请稍后再试');const stamp=new Date().toISOString();const result=await query(c,'INSERT INTO support_messages(thread_id,sender_id,role,body,request_id,created_at) VALUES(?,?,?,?,?,?)',[thread.id,user.id,agent?'staff':'user',text,requestId,stamp]);await query(c,'UPDATE support_threads SET updated_at=? WHERE id=?',[stamp,thread.id]);return {message:{id:result.insertId,role:agent?'staff':'user',text,createdAt:stamp}};});},
  async markRead(user,id,lastId){requireStaff(user);lastId=number(lastId);return tx(async c=>{const thread=await byId(id,c,true);const rows=await query(c,'SELECT COALESCE(MAX(id),0) AS maxId FROM support_messages WHERE thread_id=?',[thread.id]);await query(c,'UPDATE support_threads SET staff_read_id=GREATEST(staff_read_id,?) WHERE id=?',[Math.min(lastId,Number(rows[0].maxId)),thread.id]);return {ok:true};});},
  async close(user,id){requireStaff(user);return tx(async c=>{await byId(id,c,true);await query(c,"UPDATE support_threads SET status='closed',updated_at=? WHERE id=?",[new Date().toISOString(),number(id)]);return {ok:true};});}
 };
}
