<script setup>
import {reactive,ref,computed,watch} from 'vue';
import {state,mutate,notify,confirmAction,studentName} from '../store.js';
import {dateKey,transition} from '../domain/domain.js';
import {saveDutyPlan,repairDuty,leaveDuty,dutyRows,courseState,repairCourse,leaveCourse} from '../domain/attendance.js';
import AppIcon from './AppIcon.vue';
const types=['duty-plan','duty-repair','duty-leave','duty-detail','course-attendance','course-repair','course-leave'];
const active=computed(()=>types.includes(state.modal?.type)),type=computed(()=>state.modal?.type),form=reactive({}),error=ref('');
const lesson=computed(()=>state.data.lessons.find(l=>l.id===state.modal?.id));
const duty=computed(()=>dutyRows(state.data,state.modal?.date?.slice(0,7)||state.month).find(r=>r.date===state.modal?.date));
const course=computed(()=>lesson.value?courseState(lesson.value):null);
const clock=s=>s?new Date(s).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}):'未打卡';
const title=computed(()=>({'duty-plan':state.month+' 班次设置','duty-repair':'上下班补卡','duty-leave':'登记全天请假','duty-detail':'上下班记录','course-attendance':'课程考勤详情','course-repair':'课程补卡','course-leave':'课程请假'})[type.value]);
watch(()=>state.modal,m=>{if(!m||!types.includes(m.type))return;error.value='';Object.keys(form).forEach(k=>delete form[k]);const p=state.data.dutyPlans?.[state.month];if(m.type==='duty-plan')Object.assign(form,p?{...p,weekdays:[...p.weekdays]}:{start:'09:00',end:'18:00',weekdays:[1,2,3,4,5],grace:5,from:dateKey().startsWith(state.month)?dateKey():state.month+'-01'});if(m.type==='duty-repair'||m.type==='duty-leave'){const date=m.date||dateKey(),r=(state.data.dutyRecords||[]).find(r=>r.date===date),p=r?.plan||state.data.dutyPlans?.[date.slice(0,7)];Object.assign(form,{date,start:r?.checkIn?clock(r.checkIn):p?.start||'09:00',end:r?.checkOut?clock(r.checkOut):p?.end||'18:00',reason:''});}if(m.type==='course-repair')Object.assign(form,{start:lesson.value.checkIn?clock(lesson.value.checkIn):lesson.value.start,end:lesson.value.checkOut?clock(lesson.value.checkOut):lesson.value.end,reason:''});if(m.type==='course-leave')form.reason='';},{immediate:true});
function weekdays(n){form.weekdays=form.weekdays.includes(n)?form.weekdays.filter(x=>x!==n):[...form.weekdays,n];}
async function save(){try{const t=type.value,id=state.modal.id;if(t==='duty-repair'&&(state.data.dutyRecords||[]).some(r=>r.date===form.date)&&!await confirmAction('覆盖该日原打卡时间？原时间会保留在修正记录中。'))return;mutate(d=>{if(t==='duty-plan')saveDutyPlan(d,state.month,form);if(t==='duty-repair')repairDuty(d,form);if(t==='duty-leave')leaveDuty(d,form.date,form.reason);if(t==='course-repair')repairCourse(d,id,form);if(t==='course-leave')leaveCourse(d,id,form.reason);});state.modal=null;notify('已保存');}catch(e){error.value=e.message;}}
async function action(a){try{if(a==='restore'&&!await confirmAction('恢复待上课并清除本次考勤和收款状态？'))return;mutate(d=>transition(d,lesson.value.id,a));notify('已更新');}catch(e){error.value=e.message;}}
async function undoDuty(){try{if(!await confirmAction('撤销当日上下班记录？课程考勤和工资不受影响。'))return;mutate(d=>{d.dutyRecords=(d.dutyRecords||[]).filter(r=>r.date!==state.modal.date);});state.modal=null;notify('已撤销');}catch(e){error.value=e.message;}}
</script>
<template><view v-if="active" class="sheet-backdrop" @click.self="state.modal=null"><view class="sheet" role="dialog" aria-modal="true" :aria-label="title"><view class="sheet-heading"><text>{{title}}</text><button role="button" tabindex="0" class="icon-button" aria-label="关闭" @click="state.modal=null"><AppIcon name="close"/></button></view><scroll-view scroll-y class="sheet-scroll">
 <template v-if="type==='duty-plan'"><text class="hint">仅影响本月未打卡日期，已有记录使用打卡时的班次。</text><view class="form-columns"><view><text class="field-label">上班时间</text><picker mode="time" :value="form.start" @change="form.start=$event.detail.value"><view class="input picker-value">{{form.start}}⌄</view></picker></view><view><text class="field-label">下班时间</text><picker mode="time" :value="form.end" @change="form.end=$event.detail.value"><view class="input picker-value">{{form.end}}⌄</view></picker></view></view><text class="field-label">工作日</text><view class="workdays"><button role="button" tabindex="0" v-for="[n,label] in [[1,'一'],[2,'二'],[3,'三'],[4,'四'],[5,'五'],[6,'六'],[0,'日']]" :key="n" :class="{active:form.weekdays.includes(n)}" @click="weekdays(n)">{{label}}</button></view><text class="field-label">本月开始生效日期</text><picker mode="date" :value="form.from" :start="state.month+'-01'" @change="form.from=$event.detail.value"><view class="input picker-value">{{form.from}}⌄</view></picker><text class="field-label">迟到宽限（分钟）</text><input class="input" type="number" v-model="form.grace" aria-label="迟到宽限"/><text class="hint">超过上班时间加宽限后记迟到；早于下班时间签退记早退。当前支持当天结束的班次。</text></template>
 <template v-if="['duty-repair','duty-leave'].includes(type)"><text class="field-label">日期</text><picker mode="date" :value="form.date" @change="form.date=$event.detail.value"><view class="input picker-value">{{form.date}}⌄</view></picker></template>
 <template v-if="['duty-repair','course-repair'].includes(type)"><view class="form-columns"><view><text class="field-label">实际签到</text><picker mode="time" :value="form.start" @change="form.start=$event.detail.value"><view class="input picker-value">{{form.start}}⌄</view></picker></view><view><text class="field-label">实际签退</text><picker mode="time" :value="form.end" @change="form.end=$event.detail.value"><view class="input picker-value">{{form.end}}⌄</view></picker></view></view><text class="hint">{{type==='course-repair'?'保存后课程标记完成并按约定课时计薪，不重复累计。':'补卡会使用该日保存的班次，或该月份设置的班次。'}}不能填写未来时间。</text></template>
 <template v-if="['duty-repair','duty-leave','course-repair','course-leave'].includes(type)"><text class="field-label">{{type.includes('leave')?'请假原因':'补卡 / 修正原因'}}</text><textarea class="input textarea" v-model="form.reason" :maxlength="200" placeholder="请填写原因" aria-label="原因"/><text v-if="type==='duty-leave'" class="hint">登记全天请假，不自动扣薪；该日已有打卡时需先撤销。</text></template>
 <template v-if="type==='course-attendance'&&lesson"><view class="detail-grid"><view><text>学生</text><text>{{studentName(lesson.studentId)}}</text></view><view><text>状态</text><text>{{course.label}}</text></view><view><text>日期</text><text>{{lesson.date}}</text></view><view><text>计划</text><text>{{lesson.start}}—{{lesson.end}}</text></view><view><text>实际签到</text><text>{{clock(lesson.checkIn)}}</text></view><view><text>实际签退</text><text>{{clock(lesson.checkOut)}}</text></view></view><text v-if="lesson.leaveReason" class="note">请假原因：{{lesson.leaveReason}}</text><view class="action-grid"><button v-if="lesson.status==='scheduled'&&lesson.date===dateKey()" role="button" tabindex="0" class="primary" @click="action('start')">上课打卡</button><button v-if="lesson.status==='teaching'" role="button" tabindex="0" class="primary" @click="action('finish')">下课打卡</button><button v-if="!['leave','cancelled'].includes(lesson.status)" role="button" tabindex="0" class="secondary" @click="state.modal={type:'course-repair',id:lesson.id}">补卡 / 修正</button><button v-if="lesson.status==='scheduled'" role="button" tabindex="0" class="secondary" @click="state.modal={type:'course-leave',id:lesson.id}">登记请假</button><button v-if="lesson.status!=='scheduled'" role="button" tabindex="0" class="secondary" @click="action('restore')">恢复待上课</button></view><text v-if="lesson.attendanceEdits?.length" class="field-label">修正记录</text><view v-for="(e,i) in lesson.attendanceEdits||[]" :key="i" class="audit-row"><text>{{new Date(e.at).toLocaleString()}}</text><text>{{e.reason}}</text><text>原记录：{{clock(e.before?.checkIn)}} / {{clock(e.before?.checkOut)}}</text></view></template>
 <template v-if="type==='duty-detail'&&duty"><view class="detail-grid"><view><text>日期</text><text>{{duty.date}}</text></view><view><text>状态</text><text>{{duty.label}}</text></view><view><text>班次</text><text>{{duty.plan.start}}—{{duty.plan.end}}</text></view><view><text>时间跨度</text><text>{{+(duty.minutes/60).toFixed(2)}} 小时</text></view><view><text>上班打卡</text><text>{{clock(duty.checkIn)}}</text></view><view><text>下班打卡</text><text>{{clock(duty.checkOut)}}</text></view></view><text v-if="duty.reason" class="note">原因：{{duty.reason}}</text><view class="action-grid"><button v-if="duty.key!=='leave'" role="button" tabindex="0" class="secondary" @click="state.modal={type:'duty-repair',date:duty.date}">补卡 / 修正</button><button v-if="!duty.checkIn&&duty.key!=='leave'" role="button" tabindex="0" class="secondary" @click="state.modal={type:'duty-leave',date:duty.date}">登记请假</button><button v-if="duty.checkIn||duty.key==='leave'" role="button" tabindex="0" class="danger" @click="undoDuty">撤销当日记录</button></view><view v-for="(e,i) in duty.edits||[]" :key="i" class="audit-row"><text>{{new Date(e.at).toLocaleString()}}</text><text>{{e.reason}}</text><text>原记录：{{clock(e.before?.checkIn)}} / {{clock(e.before?.checkOut)}}</text></view></template>
 <text v-if="error" class="error" role="alert">{{error}}</text><button v-if="!['course-attendance','duty-detail'].includes(type)" role="button" tabindex="0" class="primary full save-button" @click="save">保存</button>
</scroll-view></view></view></template>
