<script setup>
import {ref,computed,onMounted,onUnmounted} from 'vue';
import {state,mutate,notify,studentName,download} from '../store.js';
import {dateKey,minutes,transition} from '../domain/domain.js';
import {courseState,dutyRows,punchDuty} from '../domain/attendance.js';
import AppIcon from './AppIcon.vue';
const mode=ref('course'),filter=ref('all'),selectedDay=ref(''),now=ref(new Date());let timer;onMounted(()=>timer=setInterval(()=>now.value=new Date(),30000));onUnmounted(()=>clearInterval(timer));
const courseRows=computed(()=>state.data.lessons.filter(l=>l.date.startsWith(state.month)).map(l=>({...l,...courseState(l,now.value),original:l})).sort((a,b)=>b.date.localeCompare(a.date)||a.start.localeCompare(b.start)));
const workRows=computed(()=>dutyRows(state.data,state.month,now.value));
const rows=computed(()=>mode.value==='course'?courseRows.value:workRows.value);
const visible=computed(()=>rows.value.filter(r=>(!selectedDay.value||r.date===selectedDay.value)&&(filter.value==='all'||(filter.value==='abnormal'?r.late||r.early||r.key==='missing':r.key===filter.value))));
const stats=computed(()=>{const r=rows.value;return {days:new Set(r.filter(x=>x.checkIn).map(x=>x.date)).size,done:r.filter(x=>x.checkOut).length,late:r.filter(x=>x.late).length,early:r.filter(x=>x.early).length,missing:r.filter(x=>x.key==='missing').length,leave:r.filter(x=>x.key==='leave').length};});
const today=computed(()=>workRows.value.find(r=>r.date===dateKey(now.value)));
const plan=computed(()=>state.data.dutyPlans?.[state.month]);
const calendar=computed(()=>{const first=new Date(state.month+'-01T12:00:00'),offset=(first.getDay()+6)%7,days=new Date(first.getFullYear(),first.getMonth()+1,0).getDate();return [...Array(offset).fill(null),...Array.from({length:days},(_,i)=>{const date=state.month+'-'+String(i+1).padStart(2,'0'),list=rows.value.filter(r=>r.date===date);return {date,day:i+1,key:list.some(r=>r.key==='missing'||r.late||r.early)?'abnormal':list.some(r=>r.key==='leave')?'leave':list.some(r=>r.checkOut)?'normal':''};})];});
const clock=s=>s?new Date(s).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}):'未打卡';
function changeMonth(n){const d=new Date(state.month+'-01T12:00:00');d.setMonth(d.getMonth()+n);state.month=dateKey(d).slice(0,7);selectedDay.value='';}
function changeMode(m){mode.value=m;filter.value='all';selectedDay.value='';}
async function punch(action){try{mutate(d=>punchDuty(d,action));now.value=new Date();notify('打卡成功');}catch(e){notify(e.message);}}
function open(r){state.modal=mode.value==='course'?{type:'course-attendance',id:r.id}:{type:'duty-detail',date:r.date};}
function exportCsv(){const cell=v=>'"'+(/^[=+\-@\t\r]/.test(String(v))?"'":'')+String(v??'').replaceAll('"','""')+'"';const data=[['日期',mode.value==='course'?'学生':'类型','计划开始','计划结束','实际签到','实际签退','状态','来源','备注'],...visible.value.map(r=>[r.date,mode.value==='course'?studentName(r.studentId):'上下班',r.start||r.plan.start,r.end||r.plan.end,r.checkIn||'',r.checkOut||'',r.label,r.manual?'补卡':'打卡',r.leaveReason||r.reason||r.attendanceEdits?.at(-1)?.reason||''])];download(`${state.month}-${mode.value==='course'?'课程':'上下班'}考勤.csv`,'\ufeff'+data.map(r=>r.map(cell).join(',')).join('\r\n'),'text/csv');}
</script>
<template><view class="attendance-page"><view class="utility-title"><text>考勤</text><button role="button" tabindex="0" class="text-action" @click="exportCsv">导出</button></view>
 <view class="attendance-tabs"><button role="button" tabindex="0" :class="{active:mode==='course'}" @click="changeMode('course')">课程考勤</button><button role="button" tabindex="0" :class="{active:mode==='duty'}" @click="changeMode('duty')">上下班考勤</button></view>
 <view class="month-row"><button role="button" tabindex="0" class="icon-button" aria-label="上个月" @click="changeMonth(-1)"><AppIcon name="left"/></button><picker mode="date" fields="month" :value="state.month" @change="state.month=$event.detail.value.slice(0,7);selectedDay='' "><text class="month-title">{{state.month.replace('-','年')}}月⌄</text></picker><button role="button" tabindex="0" class="icon-button" aria-label="下个月" @click="changeMonth(1)"><AppIcon name="arrow"/></button></view>
 <template v-if="mode==='duty'"><view class="duty-clock"><view class="spread"><text>{{state.month===dateKey().slice(0,7)?'今日打卡':'本月班次'}}</text><button role="button" tabindex="0" class="text-action" @click="state.modal={type:'duty-plan'}">班次设置</button></view><text class="hint">{{plan?`${plan.start}—${plan.end} · ${plan.from}起生效`:'尚未设置班次，设置后统计缺卡、迟到和早退。'}}</text><template v-if="state.month===dateKey().slice(0,7)"><view class="clock-times"><view><text>上班</text><text>{{clock(today?.checkIn)}}</text></view><view><text>下班</text><text>{{clock(today?.checkOut)}}</text></view></view><view class="two-buttons"><button role="button" tabindex="0" class="primary" :disabled="!today||!!today.checkIn||today.key==='leave'" @click="punch('in')">上班打卡</button><button role="button" tabindex="0" class="secondary" :disabled="!today?.checkIn||!!today.checkOut||today.key==='leave'" @click="punch('out')">下班打卡</button></view><text v-if="plan&&!today" class="hint">今天不在工作日或生效日期范围内。</text></template><view class="attendance-tools"><button role="button" tabindex="0" @click="state.modal={type:'duty-repair',date:state.month===dateKey().slice(0,7)?dateKey():state.month+'-01'}">补卡 / 修正</button><button role="button" tabindex="0" @click="state.modal={type:'duty-leave',date:state.month===dateKey().slice(0,7)?dateKey():state.month+'-01'}">登记请假</button></view></view></template>
 <view class="attendance-stats"><view v-for="[count,label] in [[stats.days,'出勤天数'],[stats.late,'迟到'],[stats.early,'早退'],[stats.missing,'缺卡'],[stats.leave,'请假']]" :key="label"><text>{{count}}</text><text>{{label}}</text></view></view>
 <view class="calendar-grid"><text v-for="day in '一二三四五六日'" :key="day" class="weekday">{{day}}</text><button role="button" tabindex="0" v-for="(day,i) in calendar" :key="i" :disabled="!day" :class="['calendar-day',day?.key,{selected:day?.date===selectedDay}]" :aria-label="day?.date||'空白'" @click="selectedDay=selectedDay===day.date?'':day.date"><text>{{day?.day}}</text><view v-if="day?.key" class="day-dot"/></button></view><view class="attendance-legend"><text>● 正常</text><text>● 异常/缺卡</text><text>● 请假</text></view>
 <view class="attendance-filters"><button role="button" tabindex="0" v-for="[key,label] in [['all','全部'],['abnormal','异常/缺卡'],['normal','正常'],['leave','请假'],['pending','待打卡']]" :key="key" :class="{active:filter===key}" @click="filter=key">{{label}}</button></view>
 <view class="spread attendance-list-title"><text>{{selectedDay||'本月'}}记录</text><button v-if="selectedDay" role="button" tabindex="0" class="text-action" @click="selectedDay=''">查看整月</button></view>
 <view v-if="!visible.length" class="empty-state"><text>没有符合条件的记录</text><text class="subtle">{{mode==='duty'&&!plan?'先设置本月班次。':'可以切换日期或状态查看。'}}</text></view>
 <button role="button" tabindex="0" v-for="r in visible" :key="r.id||r.date" class="attendance-record" @click="open(r)"><view class="spread"><text class="record-name">{{mode==='course'?studentName(r.studentId)+' · '+(r.subject||'辅导'):r.date}}</text><text :class="['attendance-status',r.key]">{{r.label}}</text></view><text class="subtle">{{mode==='course'?r.date+' ':''}}{{r.start||r.plan.start}}—{{r.end||r.plan.end}}</text><view class="spread"><text class="record-clock">{{clock(r.checkIn)}} / {{clock(r.checkOut)}}</text><text class="subtle">{{r.manual?'补卡记录':'查看详情'}} ›</text></view></button>
 <text class="hint">{{mode==='course'?'课程结束后未签到或签退会显示缺卡。补卡按实际时间判断迟到、早退；课酬仍按约定时长计算。':'上下班与课程分别记录。出勤时长为签到至签退的时间跨度，未扣除休息；请假和异常不自动扣工资。'}}</text>
</view></template>
