<script setup>
import {ref,computed} from 'vue';
import {appearance,saveAppearance,chooseWallpaper,wallpaperStyle,themeStyle} from '../appearance.js';
import {resolveAppearance} from '../domain/appearance.js';
import {state,notify,confirmAction} from '../store.js';
import AppIcon from './AppIcon.vue';
const pages=[['schedule','课表'],['students','学生'],['payroll','薪资'],['attendance','考勤'],['profile','个人中心'],['details','个人资料'],['login','登录']];
const selected=ref(state.tab),busy=ref(false),p=computed(()=>resolveAppearance(appearance.pages,selected.value));
function update(patch){try{saveAppearance(selected.value,patch);}catch(e){notify('保存失败：'+e.message);}}
async function choose(){busy.value=true;try{const image=await chooseWallpaper();if(image)update({image});}catch(e){notify(e.message);}finally{busy.value=false;}}
async function applyAll(){if(await confirmAction('把当前背景和透明度应用到全部页面？原页面背景会被替换。')){try{saveAppearance('all',p.value);notify('已应用到全部页面');}catch(e){notify('保存失败：'+e.message);}}}
</script>
<template><view class="appearance-settings"><view class="detail-navbar"><button role="button" tabindex="0" class="icon-button" aria-label="返回" @click="appearance.open=false"><AppIcon name="left"/></button><text>页面背景</text><view class="nav-spacer"/></view><view class="appearance-content"><text class="hint">{{state.user?'每个页面可单独设置，修改后自动同步到账号。':'每个页面可单独设置，登录后可云端保存。'}}</text><view class="page-options"><button role="button" tabindex="0" v-for="[key,label] in pages" :key="key" :class="{active:selected===key}" @click="selected=key">{{label}}</button></view><view class="wall-preview" :style="{...wallpaperStyle(selected),...themeStyle(selected)}"><view v-if="p.image" class="wall-preview-shade"/><view class="preview-content"><text>{{pages.find(x=>x[0]===selected)[1]}}</text><view class="preview-card" :style="p.image?{background:'var(--wall-surface)',color:'var(--wall-ink)'}:{}"><text>页面内容预览</text><text>背景完整展示，组件轻透呈现</text></view></view><text v-if="!p.image" class="preview-empty">尚未设置背景</text></view><view class="two-buttons"><button role="button" tabindex="0" class="primary" :disabled="busy" @click="choose">{{busy?'处理图片…':'从相册选择背景'}}</button><button role="button" tabindex="0" class="secondary" @click="update({image:''})">恢复默认</button></view><view class="settings-section"><text class="field-label">图片显示</text><view class="two-buttons"><button role="button" tabindex="0" :class="p.fit==='contain'?'primary':'secondary'" @click="update({fit:'contain'})">完整显示</button><button role="button" tabindex="0" :class="p.fit==='cover'?'primary':'secondary'" @click="update({fit:'cover'})">铺满屏幕</button></view><text class="hint">完整显示不裁剪图片，留白使用深色底；铺满可能裁切边缘。</text><text class="field-label">组件不透明度 {{p.opacity}}%（0%为全透明）</text><slider :value="p.opacity" :min="0" :max="70" activeColor="#8e6aa9" @change="update({opacity:$event.detail.value})"/><text class="field-label">背景明暗遮罩 {{p.shade}}%</text><slider :value="p.shade" :min="0" :max="60" activeColor="#8e6aa9" @change="update({shade:$event.detail.value})"/><text class="field-label">文字颜色</text><view class="two-buttons"><button role="button" tabindex="0" :class="p.tone==='light'?'primary':'secondary'" @click="update({tone:'light'})">浅色文字</button><button role="button" tabindex="0" :class="p.tone==='dark'?'primary':'secondary'" @click="update({tone:'dark'})">深色文字</button></view><text class="field-label">水平位置 {{p.position}}%</text><slider :value="p.position" :min="0" :max="100" activeColor="#8e6aa9" @change="update({position:$event.detail.value})"/></view><button role="button" tabindex="0" class="secondary full" @click="applyAll">应用到全部页面</button><text class="hint">建议组件不透明度 8%～20%、遮罩 10%～20%。也可设为0%，完整保留原图。输入框与弹层使用较高对比度，避免编辑时看不清。</text></view></view></template>
