<script setup>
import CharacterImage from './CharacterImage.vue';
import {ref,reactive,computed,watch} from 'vue';
import {state,CHARACTER,mutate,notify,confirmAction,saveProfile,seedDemo,canDemo,exportBackup,importBackup,signout,download,studentName,statusLabels,navigate} from '../store.js';
import {dateKey,money,amount,minutes,saveStudent,scheduleLessons,updateLesson,transition} from '../domain/domain.js';
import {salarySummary,saveSalarySettings,addCommission} from '../domain/salary.js';
import AppIcon from './AppIcon.vue';
const form=reactive({}),error=ref(''),active=computed(()=>['duty-plan','duty-repair','duty-leave','duty-detail','course-attendance','course-repair','course-leave'].includes(state.modal?.type)?null:state.modal),type=computed(()=>active.value?.type),lesson=computed(()=>state.data.lessons.find(l=>l.id===active.value?.id)),student=computed(()=>state.data.students.find(s=>s.id===active.value?.id));
const available=computed(()=>state.data.students.filter(s=>!s.archived));
const recruited=computed(()=>state.data.students.filter(s=>s.selfRecruited));
const title=computed(()=>({profile:'编辑个人资料',salary:state.month+' 薪资设置',commission:'记录招生缴费',student:active.value?.id?'编辑学生':'添加学生',lesson:active.value?.id?'修改课程':'安排新课程','student-detail':student.value?.name||'学生资料','lesson-detail':lesson.value?studentName(lesson.value.studentId)+'的课程':'课程详情',backup:'数据与备份',support:'人工客服 · 辉辉',about:'关于课笺',account:'账号与登录','export-salary':'导出工资账单'})[type.value]||'' );
watch(()=>state.modal, m=>{Object.keys(form).forEach(k=>delete form[k]);error.value='';if(!m)return;if(m.type==='profile')Object.assign(form,state.profile);if(m.type==='salary'){const s=salarySummary(state.data,state.month);Object.assign(form,{base:String(s.base/100),eveningRate:String(s.eveningRate/100),eveningCount:String(s.eveningCount)});}if(m.type==='student'){const s=student.value;Object.assign(form,s?{...s,rate:String(s.rateCents/100),billingMinutes:s.billingMinutes||60}:{name:'',subject:'',rate:'',contact:'',note:'',billingMinutes:90,selfRecruited:false});}if(m.type==='lesson'){const l=lesson.value,s=l?state.data.students.find(x=>x.id===l.studentId):available.value[0];Object.assign(form,{studentId:s?.id||'',date:l?.date||state.selected,start:l?.start||'09:00',end:l?.end||'10:30',rate:String((l?.rateCents??s?.rateCents??0)/100),billingMinutes:l?(l.billingMinutes||60):(s?.billingMinutes||60),subject:l?.subject||s?.subject||'',note:l?.note||'',repeat:1});}if(m.type==='commission')Object.assign(form,{studentId:recruited.value[0]?.id||'',date:dateKey().startsWith(state.month)?dateKey():state.month+'-01',amount:'',percent:'10'});},{immediate:true});
function studentChanged(e){const s=available.value[Number(e.detail.value)];Object.assign(form,{studentId:s.id,rate:String(s.rateCents/100),billingMinutes:s.billingMinutes||60,subject:s.subject});}
function close(){state.modal=null;}
function save(){try{if(type.value==='profile')saveProfile(form);if(type.value==='salary')mutate(d=>saveSalarySettings(d,state.month,form));if(type.value==='commission')mutate(d=>addCommission(d,form));if(type.value==='student')mutate(d=>saveStudent(d,{...form,id:active.value.id}));if(type.value==='lesson'){mutate(d=>active.value.id?updateLesson(d,active.value.id,form):scheduleLessons(d,form));state.selected=form.date;}close();notify('已保存');}catch(e){error.value=e.message;}}
async function action(action){try{if(['complete','leave','cancel','restore'].includes(action)&&!await confirmAction(({complete:'按计划时间补录完成并计入课酬？',leave:'标记教师请假，这节课不计薪？',cancel:'取消这节课程？',restore:'恢复待上课？将清除本节考勤与收款标记。'})[action]))return;mutate(d=>transition(d,lesson.value.id,action));notify('已更新');}catch(e){error.value=e.message;}}
async function deleteLesson(){try{if(await confirmAction('永久删除这节课程及考勤、课酬记录？')){mutate(d=>{d.lessons=d.lessons.filter(l=>l.id!==active.value.id);});close();}}catch(e){error.value=e.message;}}
async function archive(){try{if(await confirmAction('更改归档状态？历史课程和收入会保留。')){mutate(d=>{const s=d.students.find(x=>x.id===active.value.id);s.archived=!s.archived;});close();}}catch(e){error.value=e.message;}}
function demo(){try{seedDemo();close();}catch(e){error.value=e.message;}}
async function exit(){if(await confirmAction('退出当前账号？记录仍保留在此浏览器。')){try{await signout();}catch(e){error.value=e.message;}}}
function exportCsv(){const s=salarySummary(state.data,state.month);const rows=[['日期/月份','项目','金额(元)','说明'],[state.month,'底薪',s.base/100,''],[state.month,'课时费',s.course/100,''],[state.month,'招生提成',s.commission/100,''],[state.month,'晚辅',s.evening/100,s.eveningCount+'次'],[state.month,'合计',s.total/100,'预计应得']];for(const l of state.data.lessons.filter(l=>l.status==='completed'&&l.date.startsWith(state.month)))rows.push([l.date,studentName(l.studentId),amount(l)/100,l.subject]);const cell=v=>'"'+(/^[=+\-@\t\r]/.test(String(v))?"'":'')+String(v).replaceAll('"','""')+'"';download(`课笺-${state.month}-工资.csv`,'\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\r\n'),'text/csv');close();}
const clock=s=>s?new Date(s).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}):'—';
</script>
<template><view v-if="active" class="sheet-backdrop" @click.self="close"><view class="sheet" role="dialog" aria-modal="true" :aria-label="title"><view class="sheet-heading"><text>{{title}}</text><button role="button" tabindex="0" class="icon-button" aria-label="关闭" @click="close"><AppIcon name="close"/></button></view><scroll-view scroll-y class="sheet-scroll">
 <template v-if="type==='profile'"><text class="field-label">昵称</text><input class="input" v-model="form.name" :maxlength="24" aria-label="昵称"/><text class="field-label">个人签名</text><input class="input" v-model="form.bio" :maxlength="80" aria-label="个人签名"/></template>
 <template v-if="type==='student'"><text class="field-label">学生姓名</text><input class="input" v-model="form.name" :maxlength="40" placeholder="例如：林同学" aria-label="学生姓名"/><text class="field-label">授课科目</text><input class="input" v-model="form.subject" :maxlength="40" placeholder="例如：数学 / 钢琴" aria-label="授课科目"/><text class="field-label">计费标准</text><picker :range="['按90分钟/课时，不足向上取整','按小时（兼容旧记录）']" :value="form.billingMinutes===90?0:1" @change="form.billingMinutes=Number($event.detail.value)===0?90:60"><view class="input picker-value">{{form.billingMinutes===90?'按90分钟/课时，不足向上取整':'按小时（兼容旧记录）'}}⌄</view></picker><text class="field-label">课酬单价（元）</text><input class="input" v-model="form.rate" type="digit" aria-label="课酬单价"/><text class="field-label">学生来源</text><picker :range="['机构分配','我自己招的学生']" :value="form.selfRecruited?1:0" @change="form.selfRecruited=Number($event.detail.value)===1"><view class="input picker-value">{{form.selfRecruited?'我自己招的学生':'机构分配'}}⌄</view></picker><text class="field-label">联系方式（选填）</text><input class="input" v-model="form.contact" :maxlength="80" aria-label="联系方式"/><text class="field-label">备注（选填）</text><textarea class="input textarea" v-model="form.note" :maxlength="500" aria-label="备注"/><text class="hint">调整单价仅影响之后新排的课程，历史课酬保留原值。</text></template>
 <template v-if="type==='lesson'"><view v-if="!form.studentId" class="empty-state"><text>先添加一位学生，再开始排课。</text><button role="button" tabindex="0" class="primary" @click="state.modal={type:'student'}">添加学生</button></view><template v-else><text class="field-label">学生</text><picker :disabled="!!active.id" :range="available" range-key="name" :value="Math.max(0,available.findIndex(s=>s.id===form.studentId))" @change="studentChanged"><view class="input picker-value">{{studentName(form.studentId)}}⌄</view></picker><text class="field-label">上课日期</text><picker mode="date" :value="form.date" @change="form.date=$event.detail.value"><view class="input picker-value">{{form.date}}⌄</view></picker><view class="form-columns"><view><text class="field-label">开始时间</text><picker mode="time" :value="form.start" @change="form.start=$event.detail.value"><view class="input picker-value">{{form.start}}⌄</view></picker></view><view><text class="field-label">结束时间</text><picker mode="time" :value="form.end" @change="form.end=$event.detail.value"><view class="input picker-value">{{form.end}}⌄</view></picker></view></view><text class="field-label">计费标准</text><picker :range="['按90分钟/课时，不足向上取整','按小时（兼容旧记录）']" :value="form.billingMinutes===90?0:1" @change="form.billingMinutes=Number($event.detail.value)===0?90:60"><view class="input picker-value">{{form.billingMinutes===90?'按90分钟/课时，不足向上取整':'按小时（兼容旧记录）'}}⌄</view></picker><view class="form-columns"><view><text class="field-label">课酬单价（元）</text><input class="input" v-model="form.rate" type="digit" aria-label="课酬单价"/></view><view><text class="field-label">授课科目</text><input class="input" v-model="form.subject" :maxlength="40" aria-label="授课科目"/></view></view><template v-if="!active.id"><text class="field-label">重复安排</text><picker :range="['仅这一次','每周一次，连续4周','每周一次，连续8周','每周一次，连续12周']" :value="[1,4,8,12].indexOf(form.repeat)" @change="form.repeat=[1,4,8,12][Number($event.detail.value)]"><view class="input picker-value">{{form.repeat===1?'仅这一次':'每周一次，连续'+form.repeat+'周'}}⌄</view></picker></template><text class="field-label">课程备注</text><textarea class="input textarea" v-model="form.note" :maxlength="500" aria-label="课程备注"/><text class="hint">同一时间冲突将拒绝保存；重复排课全部通过检查后一起保存。</text></template></template>
 <template v-if="type==='salary'"><text class="field-label">底薪（元 / 月）</text><input class="input" v-model="form.base" type="digit" aria-label="底薪"/><view class="form-columns"><view><text class="field-label">晚辅单价（元 / 次）</text><input class="input" v-model="form.eveningRate" type="digit" aria-label="晚辅单价"/></view><view><text class="field-label">本月晚辅次数</text><input class="input" v-model="form.eveningCount" type="number" aria-label="晚辅次数"/></view></view><text class="hint">只保存到{{state.month}}。晚辅费 = 单价 × 次数；课程单价在学生和排课时设置。</text></template>
 <template v-if="type==='commission'"><view v-if="!recruited.length" class="empty-state"><text>先将学生来源设置为“我自己招的学生”。</text><button role="button" tabindex="0" class="primary" @click="navigate('students')">去学生页面</button></view><template v-else><text class="field-label">自招学生</text><picker :range="recruited" range-key="name" @change="form.studentId=recruited[Number($event.detail.value)].id"><view class="input picker-value">{{studentName(form.studentId)}}⌄</view></picker><text class="field-label">缴费日期</text><picker mode="date" :value="form.date" @change="form.date=$event.detail.value"><view class="input picker-value">{{form.date}}⌄</view></picker><text class="field-label">学生实缴金额（元）</text><input class="input" v-model="form.amount" type="digit" aria-label="实缴金额"/><text class="field-label">提成比例（%）</text><input class="input" v-model="form.percent" type="digit" aria-label="提成比例"/><text class="hint">逐笔实缴金额 × 比例，只计入缴费月份；相同学生、日期、金额拒绝重复计提。</text></template></template>
 <template v-if="type==='student-detail'&&student"><view class="detail-grid"><view><text>科目</text><text>{{student.subject||'未设置'}}</text></view><view><text>课酬单价</text><text>¥{{money(student.rateCents)}}</text></view><view><text>计费方式</text><text>{{student.billingMinutes===90?'90分钟课时':'按小时（旧）'}}</text></view><view><text>来源</text><text>{{student.selfRecruited?'自己招的学生':'机构分配'}}</text></view></view><text v-if="student.contact" class="note">联系方式：{{student.contact}}</text><text v-if="student.note" class="note">{{student.note}}</text><view class="two-buttons"><button role="button" tabindex="0" class="primary" @click="state.modal={type:'student',id:student.id}">编辑资料</button><button role="button" tabindex="0" class="secondary" @click="archive">{{student.archived?'恢复学生':'归档学生'}}</button></view></template>
 <template v-if="type==='lesson-detail'&&lesson"><text class="badge">{{statusLabels[lesson.status]}}</text><view class="detail-grid"><view><text>日期</text><text>{{lesson.date}}</text></view><view><text>科目</text><text>{{lesson.subject||'辅导'}}</text></view><view><text>约定时段</text><text>{{lesson.start}}—{{lesson.end}}</text></view><view><text>课酬</text><text>¥{{money(amount(lesson))}}</text></view><view><text>上课打卡</text><text>{{clock(lesson.checkIn)}}</text></view><view><text>下课打卡</text><text>{{clock(lesson.checkOut)}}{{lesson.manual?'（补录）':''}}</text></view></view><text v-if="lesson.note" class="note">{{lesson.note}}</text><view class="action-grid"><template v-if="lesson.status==='scheduled'"><button role="button" tabindex="0" v-if="lesson.date===dateKey()" class="primary" @click="action('start')">上课打卡</button><button role="button" tabindex="0" v-if="lesson.date<=dateKey()" class="secondary" @click="action('complete')">补录完成</button><button role="button" tabindex="0" class="secondary" @click="state.modal={type:'lesson',id:lesson.id}">修改课程</button><button role="button" tabindex="0" class="secondary" @click="action('leave')">教师请假</button><button role="button" tabindex="0" class="secondary" @click="action('cancel')">取消课程</button></template><button role="button" tabindex="0" v-if="lesson.status==='teaching'" class="primary" @click="action('finish')">下课打卡</button><button role="button" tabindex="0" v-if="lesson.status==='completed'" class="primary" @click="action('paid')">{{lesson.paid?'撤销收款':'标记已收款'}}</button><button role="button" tabindex="0" v-if="lesson.status!=='scheduled'" class="secondary" @click="action('restore')">恢复待上课</button><button role="button" tabindex="0" class="danger" @click="deleteLesson">删除课程</button></view></template>
 <template v-if="type==='backup'"><text class="hint">数据保存在当前浏览器，清除数据前请导出备份。</text><button role="button" tabindex="0" class="service-row" @click="exportBackup"><AppIcon name="download"/><text>导出{{state.loadError?'原始':''}}备份</text></button><button role="button" tabindex="0" class="service-row" @click="importBackup"><AppIcon name="download"/><text>恢复 JSON 备份</text></button><button role="button" tabindex="0" class="service-row" :disabled="!canDemo" @click="demo"><AppIcon name="star"/><text>体验示例数据（仅空数据可用）</text></button></template>

 <template v-if="type==='about'"><view class="support-content"><CharacterImage  class="about-character" /><text class="support-title">课笺 · 我的紫色教学手账</text><text class="note">为自己的学生排好课，<br/>把每一份认真好好记下来。</text><text class="hint">库洛米图片来自三丽鸥官方网站，角色版权归Sanrio所有。本应用并非Sanrio官方应用。</text><text class="hint">当前是H5预览。鸿蒙设备适配和安装包在页面确认后进行。</text></view></template>
 <template v-if="type==='account'"><text class="note">{{state.user?.email||'当前为访客体验'}}</text><text class="hint">{{state.mode==='development'?'当前本机开发验证码不发送邮件。':'使用邮箱验证码登录。'}}每个邮箱使用独立的本机数据，当前无云同步。</text><button role="button" tabindex="0" class="primary full" @click="exit">{{state.user?'退出登录':'前往邮箱登录'}}</button></template>
 <template v-if="type==='export-salary'"><text class="note">导出{{state.month}}底薪、课时、招生、晚辅汇总及授课明细为CSV。</text><button role="button" tabindex="0" class="primary full" @click="exportCsv">下载工资账单</button></template>
 <text v-if="error" class="error" role="alert">{{error}}</text><button role="button" tabindex="0" v-if="['profile','student','salary'].includes(type)||(type==='lesson'&&form.studentId)||(type==='commission'&&recruited.length)" class="primary full save-button" @click="save">保存{{type==='lesson'?'排课':type==='student'?'学生':''}}</button>
</scroll-view></view></view></template>
