<script setup>
import CharacterImage from './CharacterImage.vue';
import {ref,onUnmounted,watch} from 'vue';
import {state,CHARACTER,api,login,enterGuest} from '../store.js';
const email=ref(''),code=ref(''),error=ref(''),hint=ref(''),remaining=ref(0),busy=ref(false);let timer;const sentEmail=ref('');
watch(email,()=>{error.value='';if(sentEmail.value&&email.value.trim().toLowerCase()!==sentEmail.value)code.value='';});
async function request(){if(!/^\S+@[^\s@]+\.[^\s@]+$/.test(email.value)){error.value='请填写有效邮箱';return;}busy.value=true;error.value='';try{const destination=email.value.trim().toLowerCase();const r=await api('/api/auth/request',{email:destination});sentEmail.value=destination;hint.value=r.devCode?`开发验证码：${r.devCode}（未发送邮件，5分钟有效）`:`验证码已发送至 ${destination}，请查看收件箱或垃圾邮件`;remaining.value=60;clearInterval(timer);timer=setInterval(()=>{if(--remaining.value<=0)clearInterval(timer);},1000);}catch(e){error.value=e.message;}finally{busy.value=false;}}
async function submit(){if(!/^[0-9]{6}$/.test(code.value)){error.value='\u8bf7\u8f93\u51656\u4f4d\u9a8c\u8bc1\u7801';return;}busy.value=true;error.value='';try{await login(email.value,code.value);}catch(e){error.value=e.message;}finally{busy.value=false;}}
onUnmounted(()=>clearInterval(timer));
</script>
<template><view class="login-page"><CharacterImage  class="login-character" /><text class="login-title">欢迎回到你的<br/>紫色小世界</text><text class="subtle">把热爱排进课表，把每一份努力记下来。</text><view v-if="state.mode!=='offline'" class="login-form"><text class="field-label">QQ邮箱 / 邮箱地址</text><input v-model="email" class="input" placeholder="请输入QQ邮箱，如 123456@qq.com" :maxlength="254" aria-label="邮箱地址"/><text class="field-label">验证码</text><view class="code-row"><input v-model="code" class="input" type="number" :maxlength="6" placeholder="6位验证码" aria-label="验证码"/><button role="button" tabindex="0" class="secondary" :disabled="busy||remaining>0||state.mode==='unavailable'" @click="request">{{remaining?remaining+'秒后重发':'发送验证码'}}</button></view><text class="hint">{{hint||(state.mode==='development'?'本机预览：验证码将在页面显示，不发送邮件。':state.mode==='unavailable'?'邮箱服务暂未连接，请稍后重试。':'验证码有效期5分钟，请勿告诉他人。')}}</text><text v-if="error" class="error" role="alert">{{error}}</text><text class="hint">首次验证自动注册账号；已有账号直接登录。登录后已保存的数据自动同步到云端，换设备登录可恢复；冲突时会提示处理。</text><button role="button" tabindex="0" class="primary full" :disabled="busy||state.mode==='unavailable'" @click="submit">注册 / 登录</button><button role="button" tabindex="0" class="text-action guest-entry" @click="enterGuest">先逛逛，体验页面</button></view><view v-if="state.mode==='offline'" class="login-form"><text class="hint">当前是离线安卓包，邮箱登录服务尚未部署。可直接使用本机功能。</text><button role="button" class="primary full" @click="enterGuest">继续离线使用</button></view><text class="page-signature">艳の辉 · 认真生活，可爱上课</text></view></template>
