<script setup>
import {ref,computed,watch} from 'vue';
import {state,cloudClient,api,download,notify,confirmAction,restoreDocument,key,currentDocument} from '../store.js';
import {cloud} from '../cloud.js';
import AppIcon from './AppIcon.vue';
const labels={signedOut:'登录后开启同步',pending:'本机已保存，等待同步',syncing:'正在同步',synced:'已同步',conflict:'有冲突，需要处理',error:'同步失败，本机已保存',unauthorized:'登录已过期，请重新登录',localConflict:'另一标签页有更新'};
const label=computed(()=>labels[cloud.status]||cloud.status),history=ref([]),busy=ref(false);
async function versions(){if(!state.user)return;try{history.value=(await api('/api/sync/history')).versions;}catch(e){notify(e.message);}}
watch(()=>cloud.open,open=>{if(open)versions();});
async function resolve(choice){if(!await confirmAction(choice==='remote'?'使用服务端版本替换本机？当前本机副本会先保存在恢复区。':'用本机版本覆盖服务端？服务端旧版本会保留在历史记录中。'))return;await cloudClient.resolve(choice);await versions();}
function exportLocal(){download('艳の辉-同步本机副本.json',JSON.stringify(currentDocument(),null,2));}
async function restore(version){const owner=key();busy.value=true;try{const snapshot=await api('/api/sync/history/'+version);if(!await confirmAction('恢复此历史版本？将先保留当前本机副本，再作为新版本同步。'))return;if(owner!==key())throw Error('账号已切换');restoreDocument(snapshot.document);await cloudClient.sync();await versions();}catch(e){notify(e.message);}finally{busy.value=false;}}
async function exportVersion(version){try{const snapshot=await api('/api/sync/history/'+version);download(`艳の辉-历史版本${version}.json`,JSON.stringify(snapshot.document,null,2));}catch(e){notify(e.message);}}
function exportRecovery(){try{download('艳の辉-本机恢复副本.json',JSON.stringify(cloudClient.recovery(),null,2));}catch(e){notify(e.message);}}
</script>
<template><view v-if="cloud.open" class="sheet-backdrop" @click.self="cloud.open=false"><view class="sheet" role="dialog" aria-modal="true" aria-label="同步与恢复"><view class="sheet-heading"><text>同步与恢复</text><button role="button" class="icon-button" aria-label="关闭" @click="cloud.open=false"><AppIcon name="close"/></button></view><scroll-view scroll-y class="sheet-scroll"><text class="note">{{label}}</text><text class="hint">{{cloud.environment==='local'?'当前连接本机测试数据库。':'当前连接云端服务器。'}}学生、课程、薪资、考勤、个人资料、背景和聊天记录均按账号同步。</text><text v-if="cloud.updatedAt" class="hint">上次同步：{{new Date(cloud.updatedAt).toLocaleString()}}</text><text v-if="cloud.message" class="error">{{cloud.message}}</text><view v-if="!state.user" class="hint">请先用邮箱登录。访客数据不会自动传入邮箱账号，可以先导出教学备份再登录导入。</view><template v-else><button role="button" class="primary full" :disabled="cloud.status==='syncing'||busy||cloud.status==='conflict'||cloud.status==='localConflict'" @click="cloudClient.sync()">立即同步</button><view class="two-buttons"><button role="button" class="secondary" @click="exportLocal">导出本机副本</button><button role="button" class="secondary" @click="exportRecovery">导出恢复副本</button></view><view v-if="cloud.status==='conflict'"><text class="hint">另一设备存在不同数据。请先导出副本，选择需要保留的版本；不会自动合并或丢弃。</text><view class="two-buttons"><button role="button" class="secondary" @click="resolve('remote')">采用服务端版本</button><button role="button" class="secondary" @click="resolve('local')">上传本机版本</button></view></view><text v-if="cloud.status==='localConflict'" class="hint">请先保存尚未提交的表单内容并导出副本，再刷新页面读取最新本机记录。</text><view class="section-head"><text class="section-name">服务端历史版本</text><button role="button" class="text-action" @click="versions">刷新</button></view><text v-if="!history.length" class="hint">尚无历史版本，首次上传后开始保留最近30次记录。</text><view v-for="v in history" :key="v.revision" class="sync-version"><view><text>版本 {{v.revision}}</text><text class="subtle">{{new Date(v.updatedAt).toLocaleString()}}</text></view><button role="button" class="text-action" @click="exportVersion(v.revision)">下载</button><button role="button" class="text-action" :disabled="busy||cloud.status==='syncing'||cloud.status==='conflict'||cloud.status==='localConflict'" @click="restore(v.revision)">恢复</button></view></template><text class="hint">历史版本不能替代异地备份。后台数据库备份还需复制到另一块磁盘或云存储。</text></scroll-view></view></view></template>
