<script setup>
import CharacterImage from './CharacterImage.vue';
import {computed,ref} from 'vue';
import {state,CHARACTER,studentName,statusLabels,mutate,notify,confirmAction} from '../store.js';
import {dateKey,addDays,minutes,money,amount,summary,transition} from '../domain/domain.js';
import {salarySummary} from '../domain/salary.js';
import AppIcon from './AppIcon.vue';
const search=ref(''),archived=ref(false);
const lessons=computed(()=>state.data.lessons.filter(l=>l.date===state.selected).sort((a,b)=>a.start.localeCompare(b.start)));
const active=computed(()=>lessons.value.filter(l=>!['leave','cancelled'].includes(l.status)));
const week=computed(()=>{const day=(new Date(state.selected+'T12:00:00').getDay()+6)%7;return Array.from({length:7},(_,i)=>addDays(state.selected,i-day));});
const students=computed(()=>state.data.students.filter(s=>(archived.value||!s.archived)&&`${s.name}${s.subject}${s.contact}`.includes(search.value)));
const sal=computed(()=>salarySummary(state.data,state.month));const stats=computed(()=>summary(state.data,state.month));
const done=computed(()=>state.data.lessons.filter(l=>l.status==='completed'&&l.date.startsWith(state.month)).sort((a,b)=>b.date.localeCompare(a.date)));
const commissions=computed(()=>(state.data.commissions||[]).filter(c=>c.date.startsWith(state.month)));
const attendance=computed(()=>state.data.lessons.filter(l=>['completed','leave','teaching'].includes(l.status)&&l.date.startsWith(state.month)).sort((a,b)=>b.date.localeCompare(a.date)));
const calendar=computed(()=>{const first=new Date(state.month+'-01T12:00:00'),offset=(first.getDay()+6)%7,count=new Date(first.getFullYear(),first.getMonth()+1,0).getDate();return [...Array(offset).fill(null),...Array.from({length:count},(_,i)=>{const date=state.month+'-'+String(i+1).padStart(2,'0');return {day:i+1,status:attendance.value.some(l=>l.date===date&&l.status==='completed')?'present':attendance.value.some(l=>l.date===date&&l.status==='leave')?'leave':''};})];});
function shiftMonth(n){const d=new Date(state.month+'-01T12:00:00');d.setMonth(d.getMonth()+n);state.month=dateKey(d).slice(0,7);}
async function act(l,action){try{mutate(d=>transition(d,l.id,action));notify('已记录');}catch(e){notify(e.message);}}
async function removeCommission(c){try{if(await confirmAction('删除这笔缴费及其招生提成？'))mutate(d=>{d.commissions=d.commissions.filter(x=>x.id!==c.id);});}catch(e){notify(e.message);}}
const time=s=>s?new Date(s).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}):'—';
</script>
<template><view class="teaching-page">
 <view class="page-heading"><view><text class="eyeline">{{({schedule:'把今天，安排成喜欢的样子',students:'陪伴每一点小进步',payroll:'每一份努力，都值得被记录',attendance:'认真上课，轻松记录'})[state.tab]}}</text><text class="page-title">{{({schedule:'我的课表',students:'我的学生',payroll:'我的薪资',attendance:'我的考勤'})[state.tab]}}</text></view><button role="button" tabindex="0" v-if="['schedule','students'].includes(state.tab)" class="primary compact" @click="state.modal={type:state.tab==='students'?'student':'lesson'}"><text>＋</text>{{state.tab==='students'?'添加':'排课'}}</button></view>
 <template v-if="state.tab==='schedule'">
  <view class="schedule-banner"><view><text>今天的认真，<br/>是明天的小小底气。</text><text>和库洛米一起，好好上课</text></view><CharacterImage   /></view>
  <view class="month-row"><picker mode="date" :value="state.selected" @change="state.selected=$event.detail.value"><text class="month-title">{{state.selected.slice(0,7).replace('-','年')}}月⌄</text></picker><view class="row"><button role="button" tabindex="0" class="icon-button" aria-label="上一周" @click="state.selected=addDays(state.selected,-7)"><AppIcon name="left"/></button><button role="button" tabindex="0" class="text-action" @click="state.selected=dateKey()">今天</button><button role="button" tabindex="0" class="icon-button" aria-label="下一周" @click="state.selected=addDays(state.selected,7)"><AppIcon name="arrow"/></button></view></view>
  <view class="week-strip"><button role="button" tabindex="0" v-for="(day,i) in week" :key="day" :class="['week-day',{selected:day===state.selected}]" @click="state.selected=day"><text>{{'一二三四五六日'[i]}}</text><text>{{Number(day.slice(8))}}</text><view v-if="state.data.lessons.some(l=>l.date===day&&!['cancelled','leave'].includes(l.status))" class="day-dot"/></button></view>
  <view class="overview"><view><text>今日课程</text><text>{{active.length}} <small>节</small></text></view><view><text>计划时长</text><text>{{+(active.reduce((n,l)=>n+minutes(l.end)-minutes(l.start),0)/60).toFixed(2)}} <small>小时</small></text></view><view><text>预计课酬</text><text>¥{{money(active.reduce((n,l)=>n+amount(l),0))}}</text></view></view>
  <view class="section-head"><text class="section-name">课程安排</text><text class="subtle">{{lessons.filter(l=>l.status==='completed').length}} 节已完成</text></view>
  <view v-if="!lessons.length" class="empty-state"><AppIcon name="schedule" :size="36"/><text>这一天还没有课程</text><text class="subtle">留一点时间给自己，也给新的安排。</text><button role="button" tabindex="0" class="secondary" @click="state.modal={type:'lesson'}">安排一节课</button></view>
  <view v-for="l in lessons" :key="l.id" class="lesson-row"><view class="lesson-time"><text>{{l.start}}</text><text>{{l.end}}</text></view><view class="lesson-card"><button role="button" tabindex="0" class="lesson-main" @click="state.modal={type:'lesson-detail',id:l.id}"><view class="spread"><text class="student-name">{{studentName(l.studentId)}}</text><text :class="['badge',l.status]">{{statusLabels[l.status]}}</text></view><text class="subtle">{{l.subject||'个别辅导'}} · {{(minutes(l.end)-minutes(l.start))/60}}小时</text><text v-if="l.note" class="subtle">{{l.note}}</text></button><view class="spread lesson-bottom"><text class="price">¥{{money(amount(l))}}</text><button role="button" tabindex="0" v-if="l.status==='teaching'" class="secondary mini" @click="act(l,'finish')">下课打卡</button><button role="button" tabindex="0" v-else-if="l.status==='scheduled'&&l.date===dateKey()" class="secondary mini" @click="act(l,'start')">上课打卡</button><button role="button" tabindex="0" v-else class="secondary mini" @click="state.modal={type:'lesson-detail',id:l.id}">查看详情</button></view></view></view>
 </template>
 <template v-if="state.tab==='students'"><input class="input search" v-model="search" placeholder="搜索姓名、科目、联系方式" aria-label="搜索学生"/><button role="button" tabindex="0" class="archive-filter" @click="archived=!archived"><text>{{archived?'☑':'□'}}</text> 显示已归档学生</button><view v-if="!students.length" class="empty-state"><AppIcon name="students" :size="36"/><text>从第一位学生开始</text><button role="button" tabindex="0" class="primary" @click="state.modal={type:'student'}">添加学生</button></view><button role="button" tabindex="0" v-for="s in students" :key="s.id" class="student-row" @click="state.modal={type:'student-detail',id:s.id}"><view class="letter-avatar">{{s.name.slice(0,1)}}</view><view class="student-info"><text>{{s.name}} <text v-if="s.selfRecruited" class="badge">自招</text><text v-if="s.archived" class="badge">已归档</text></text><text>{{s.subject||'未设置科目'}} · {{state.data.lessons.filter(l=>l.studentId===s.id&&l.status==='completed').length}} 节已完成</text></view><view class="rate"><text>¥{{money(s.rateCents)}}</text><text>{{s.billingMinutes===90?'/ 90分钟课时':'/ 小时（旧）'}}</text></view></button></template>
 <template v-if="['payroll','attendance'].includes(state.tab)"><view class="month-row"><button role="button" tabindex="0" class="icon-button" aria-label="上个月" @click="shiftMonth(-1)"><AppIcon name="left"/></button><picker mode="date" fields="month" :value="state.month" @change="state.month=$event.detail.value.slice(0,7)"><text class="month-title">{{state.month.replace('-','年')}}月⌄</text></picker><button role="button" tabindex="0" class="icon-button" aria-label="下个月" @click="shiftMonth(1)"><AppIcon name="arrow"/></button></view></template>
 <template v-if="state.tab==='payroll'"><view class="salary-hero"><text>本月预计总薪资</text><text class="salary-total">¥{{money(sal.total)}}</text><view class="salary-meta"><text>完成 {{stats.completed}} 节</text><text>晚辅 {{sal.eveningCount}} 次</text><text>招生 {{sal.recruited}} 人</text></view></view><view class="salary-grid"><view v-for="[name,value,note] in [['固定底薪',sal.base,'本月固定金额'],['课时费',sal.course,sal.units+'个90分钟课时'+(sal.legacyCount?' + '+sal.legacyCount+'节旧计费课程':'')],['招生提成',sal.commission,commissions.length+'笔缴费，逐笔计算'],['晚辅费',sal.evening,'¥'+money(sal.eveningRate)+'/次 × '+sal.eveningCount+'次']]" :key="name" class="salary-part"><text>{{name}}</text><text>¥{{money(value)}}</text><text>{{note}}</text></view></view><view class="two-buttons"><button role="button" tabindex="0" class="secondary" @click="state.modal={type:'salary'}">底薪 / 晚辅设置</button><button role="button" tabindex="0" class="primary" @click="state.modal={type:'commission'}">记录招生缴费</button></view><text class="formula">总薪资 = 底薪 + 课时费 + 招生提成 + 晚辅费。90分钟为1课时，不足向上取整；缴费只计入缴费月份。</text><view class="section-head"><text class="section-name">招生提成</text><text class="subtle">{{sal.recruited}}位自招学生</text></view><text v-if="!commissions.length" class="hint">还没有缴费记录。先在学生资料里设置自招来源。</text><view v-for="c in commissions" :key="c.id" class="commission-row"><view><text>{{studentName(c.studentId)}}</text><text class="subtle">{{c.date}} · ¥{{money(c.tuitionCents)}} × {{c.basisPoints/100}}%</text></view><text class="price">¥{{money(Math.round(c.tuitionCents*c.basisPoints/10000))}}</text><button role="button" tabindex="0" class="text-action danger-text" @click="removeCommission(c)">删除</button></view><view class="section-head"><text class="section-name">授课明细</text><button role="button" tabindex="0" class="text-action" @click="state.modal={type:'export-salary'}">导出账单</button></view><text v-if="!done.length" class="hint">课程完成后，课酬会显示在这里。</text><view v-for="l in done" :key="l.id" class="ledger-row"><button role="button" tabindex="0" @click="state.modal={type:'lesson-detail',id:l.id}"><text>{{studentName(l.studentId)}} · {{l.subject}}</text><text class="subtle">{{l.date}} {{l.start}}—{{l.end}}</text><text class="subtle">{{l.billingMinutes===90?Math.ceil((minutes(l.end)-minutes(l.start))/90)+'课时':'旧规则按小时'}}</text></button><view><text class="price">¥{{money(amount(l))}}</text><button role="button" tabindex="0" class="text-action" @click="act(l,'paid')">{{l.paid?'已收款 ✓':'标记收款'}}</button></view></view></template>
 <template v-if="state.tab==='attendance'"><view class="stats-grid"><view v-for="[value,label] in [[stats.days,'出勤天数'],[stats.late,'迟到次数'],[stats.leave,'请假节数']]" :key="label"><text>{{value}}</text><text>{{label}}</text></view></view><view class="calendar-grid"><text v-for="day in '一二三四五六日'" :key="day" class="weekday">{{day}}</text><view v-for="(c,i) in calendar" :key="i" :class="['calendar-day',c?.status]"><text>{{c?.day}}</text><view v-if="c?.status" class="day-dot" /></view></view><text class="hint">紫色为完成授课 · 浅黄为请假</text><view class="section-head"><text class="section-name">出勤记录</text><text class="subtle">打卡 / 手动补录</text></view><view v-if="!attendance.length" class="empty-state"><AppIcon name="attendance" :size="36"/><text>还没有考勤记录</text><text class="subtle">在课表中上下课打卡，或为历史课程补录。</text></view><button role="button" tabindex="0" v-for="l in attendance" :key="l.id" class="footprint" @click="state.modal={type:'lesson-detail',id:l.id}"><view class="footprint-date"><text>{{Number(l.date.slice(8))}}</text><text>{{Number(l.date.slice(5,7))}}月</text></view><view class="footprint-main"><text>{{studentName(l.studentId)}} · {{l.subject}}</text><text>{{l.status==='leave'?'教师请假 · 不计课酬':time(l.checkIn)+'—'+time(l.checkOut)+' · '+(l.manual?'补录':'实际打卡')}}</text></view><text class="badge">{{statusLabels[l.status]}}</text></button><text class="hint">签到超过计划开始5分钟记迟到，不自动扣薪；补录不判断迟到。</text></template>
</view></template>
