const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export let user=null,mode='development',guest=sessionStorage.getItem('kejian-guest')==='true';
export async function api(path,data){const res=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const body=await res.json();if(!res.ok)throw Error(body.error||'请求失败');return body;}
export async function initializeAccount(){try{const result=await api('/api/session');user=result.user;mode=result.mode;}catch{mode='unavailable';}return user;}
export const storageKey=()=>user?`kejian-account-${user.email}`:'kejian-data';
export function loginPage(){return `<section class="login-page"><div class="login-art"><span class="spark a">✦</span><img src="kuromi.svg" alt="库洛米"><span class="spark b">✧</span></div><h1>欢迎回到你的<br>紫色小世界</h1><p class="muted">把热爱排进课表，把每一份努力记下来。</p><form id="login-form"><label class="field">邮箱地址<input type="email" name="email" required autocomplete="email" placeholder="请输入你的邮箱"></label><label class="field">验证码<div class="code-row"><input name="code" required inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" placeholder="6 位验证码"><button type="button" class="btn secondary" id="request-code">获取验证码</button></div></label><p id="code-hint" class="hint">${mode==='development'?'当前为本机预览：验证码会在页面显示，不发送邮件。':mode==='email'?'验证码将发送至你的邮箱，5分钟内有效。':'登录服务尚未连接，可先预览页面。'}</p><p class="error" role="alert"></p><button class="btn primary full" type="submit">登录 / 注册</button></form><button class="guest-button" id="guest-entry">先逛逛，体验页面</button><p class="login-foot">课笺 · 认真生活，可爱上课</p></section>`;}
let cooldown;
export function bindLogin(onLogin){document.getElementById('guest-entry')?.addEventListener('click',()=>{guest=true;sessionStorage.setItem('kejian-guest','true');onLogin();});const form=document.getElementById('login-form');if(!form)return;const error=form.querySelector('.error');document.getElementById('request-code').onclick=async()=>{const email=form.elements.email;if(!email.reportValidity())return;const button=document.getElementById('request-code');button.disabled=true;error.textContent='';try{const r=await api('/api/auth/request',{email:email.value});document.getElementById('code-hint').textContent=r.mode==='development'?`开发验证码：${r.devCode}（未发送邮件，5分钟有效）`:'验证码已发送，请查收邮箱（包括垃圾邮件）。';let left=60;button.textContent=`${left}秒后重发`;clearInterval(cooldown);cooldown=setInterval(()=>{left--;button.textContent=left?`${left}秒后重发`:'重新获取';if(!left){clearInterval(cooldown);button.disabled=false;}},1000);}catch(e){error.textContent=e.message;button.disabled=false;}};form.onsubmit=async e=>{e.preventDefault();e.stopImmediatePropagation();const button=form.querySelector('[type=submit]');button.disabled=true;error.textContent='';try{const r=await api('/api/auth/verify',{email:form.elements.email.value,code:form.elements.code.value});user=r.user;guest=false;sessionStorage.removeItem('kejian-guest');clearInterval(cooldown);onLogin();}catch(e){error.textContent=e.message;}finally{button.disabled=false;}};}
export async function logout(){await api('/api/auth/logout',{});user=null;guest=false;sessionStorage.removeItem('kejian-guest');}
export function showLogin(){guest=false;sessionStorage.removeItem('kejian-guest');}
export const accountLabel=()=>user?esc(user.email):'访客体验 · 数据保存在当前浏览器';
